// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Catalog level attribute config.
public struct AttributesConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Immutable. The fully qualified resource name of the attribute
  /// config. Format: `projects/*/locations/*/catalogs/*/attributesConfig`
  public var name: Swift.String = Swift.String()

  /// Enable attribute(s) config at catalog level.
  /// For example, indexable, dynamic_facetable, or searchable for each
  /// attribute.
  ///
  /// The key is catalog attribute's name.
  /// For example: `color`, `brands`, `attributes.custom_attribute`, such as
  /// `attributes.xyz`.
  ///
  /// The maximum number of catalog attributes allowed in a request is 1000.
  public var catalogAttributes: [Swift.String: CatalogAttribute] = [:]

  /// Output only. The
  /// [AttributeConfigLevel][google.cloud.retail.v2.AttributeConfigLevel] used
  /// for this catalog.
  ///
  /// [google.cloud.retail.v2.AttributeConfigLevel]: <doc:AttributeConfigLevel>
  public var attributeConfigLevel: AttributeConfigLevel = AttributeConfigLevel()

  /// Initialize a new instance of `AttributesConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AttributesConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.AttributesConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
