// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Catalog level attribute config for an attribute. For example, if customers
/// want to enable/disable facet for a specific attribute.
public struct CatalogAttribute: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Attribute name.
  /// For example: `color`, `brands`, `attributes.custom_attribute`, such as
  /// `attributes.xyz`.
  /// To be indexable, the attribute name can contain only alpha-numeric
  /// characters and underscores. For example, an attribute named
  /// `attributes.abc_xyz` can be indexed, but an attribute named
  /// `attributes.abc-xyz` cannot be indexed.
  ///
  /// If the attribute key starts with `attributes.`, then the attribute is a
  /// custom attribute. Attributes such as `brands`, `patterns`, and `title` are
  /// built-in and called system attributes.
  public var key: Swift.String = Swift.String()

  /// Output only. Indicates whether this attribute has been used by any
  /// products. `True` if at least one [Product][google.cloud.retail.v2.Product]
  /// is using this attribute in
  /// [Product.attributes][google.cloud.retail.v2.Product.attributes]. Otherwise,
  /// this field is `False`.
  ///
  /// [CatalogAttribute][google.cloud.retail.v2.CatalogAttribute] can be
  /// pre-loaded by using
  /// [CatalogService.AddCatalogAttribute][google.cloud.retail.v2.CatalogService.AddCatalogAttribute]
  /// or
  /// [CatalogService.UpdateAttributesConfig][google.cloud.retail.v2.CatalogService.UpdateAttributesConfig]
  /// APIs. This field is `False` for pre-loaded
  /// [CatalogAttribute][google.cloud.retail.v2.CatalogAttribute]s.
  ///
  /// Only pre-loaded [catalog
  /// attributes][google.cloud.retail.v2.CatalogAttribute] that are neither in
  /// use by products nor predefined can be deleted. [Catalog
  /// attributes][google.cloud.retail.v2.CatalogAttribute] that are
  /// either in use by products or are predefined attributes cannot be deleted;
  /// however, their configuration properties will reset to default values upon
  /// removal request.
  ///
  /// After catalog changes, it takes about 10 minutes for this field to update.
  ///
  /// [google.cloud.retail.v2.CatalogAttribute]: <doc:CatalogAttribute>
  /// [google.cloud.retail.v2.CatalogService.AddCatalogAttribute]: <doc:CatalogServiceClient/addCatalogAttribute(request:options:)>
  /// [google.cloud.retail.v2.CatalogService.UpdateAttributesConfig]: <doc:CatalogServiceClient/updateAttributesConfig(request:options:)>
  /// [google.cloud.retail.v2.Product]: <doc:Product>
  /// [google.cloud.retail.v2.Product.attributes]: <doc:Product/attributes>
  public var inUse: Swift.Bool = Swift.Bool()

  /// Output only. The type of this attribute. This is derived from the attribute
  /// in [Product.attributes][google.cloud.retail.v2.Product.attributes].
  ///
  /// [google.cloud.retail.v2.Product.attributes]: <doc:Product/attributes>
  public var type: CatalogAttribute.AttributeType = CatalogAttribute.AttributeType()

  /// When
  /// [AttributesConfig.attribute_config_level][google.cloud.retail.v2.AttributesConfig.attribute_config_level]
  /// is CATALOG_LEVEL_ATTRIBUTE_CONFIG, if INDEXABLE_ENABLED attribute values
  /// are indexed so that it can be filtered, faceted, or boosted in
  /// [SearchService.Search][google.cloud.retail.v2.SearchService.Search].
  ///
  /// Must be specified when
  /// [AttributesConfig.attribute_config_level][google.cloud.retail.v2.AttributesConfig.attribute_config_level]
  /// is CATALOG_LEVEL_ATTRIBUTE_CONFIG, otherwise throws INVALID_FORMAT error.
  ///
  /// [google.cloud.retail.v2.AttributesConfig.attribute_config_level]: <doc:AttributesConfig/attributeConfigLevel>
  /// [google.cloud.retail.v2.SearchService.Search]: <doc:SearchServiceClient/search(request:options:)>
  public var indexableOption: CatalogAttribute.IndexableOption = CatalogAttribute.IndexableOption()

  /// If DYNAMIC_FACETABLE_ENABLED, attribute values are available for dynamic
  /// facet. Could only be DYNAMIC_FACETABLE_DISABLED if
  /// [CatalogAttribute.indexable_option][google.cloud.retail.v2.CatalogAttribute.indexable_option]
  /// is INDEXABLE_DISABLED. Otherwise, an INVALID_ARGUMENT error is returned.
  ///
  /// Must be specified, otherwise throws INVALID_FORMAT error.
  ///
  /// [google.cloud.retail.v2.CatalogAttribute.indexable_option]: <doc:CatalogAttribute/indexableOption>
  public var dynamicFacetableOption: CatalogAttribute.DynamicFacetableOption =
    CatalogAttribute.DynamicFacetableOption()

  /// When
  /// [AttributesConfig.attribute_config_level][google.cloud.retail.v2.AttributesConfig.attribute_config_level]
  /// is CATALOG_LEVEL_ATTRIBUTE_CONFIG, if SEARCHABLE_ENABLED, attribute values
  /// are searchable by text queries in
  /// [SearchService.Search][google.cloud.retail.v2.SearchService.Search].
  ///
  /// If SEARCHABLE_ENABLED but attribute type is numerical, attribute values
  /// will not be searchable by text queries in
  /// [SearchService.Search][google.cloud.retail.v2.SearchService.Search], as
  /// there are no text values associated to numerical attributes.
  ///
  /// Must be specified, when
  /// [AttributesConfig.attribute_config_level][google.cloud.retail.v2.AttributesConfig.attribute_config_level]
  /// is CATALOG_LEVEL_ATTRIBUTE_CONFIG, otherwise throws INVALID_FORMAT error.
  ///
  /// [google.cloud.retail.v2.AttributesConfig.attribute_config_level]: <doc:AttributesConfig/attributeConfigLevel>
  /// [google.cloud.retail.v2.SearchService.Search]: <doc:SearchServiceClient/search(request:options:)>
  public var searchableOption: CatalogAttribute.SearchableOption =
    CatalogAttribute.SearchableOption()

  /// If EXACT_SEARCHABLE_ENABLED, attribute values will be exact searchable.
  /// This property only applies to textual custom attributes and requires
  /// indexable set to enabled to enable exact-searchable. If unset, the server
  /// behavior defaults to
  /// [EXACT_SEARCHABLE_DISABLED][google.cloud.retail.v2.CatalogAttribute.ExactSearchableOption.EXACT_SEARCHABLE_DISABLED].
  ///
  /// [google.cloud.retail.v2.CatalogAttribute.ExactSearchableOption.EXACT_SEARCHABLE_DISABLED]: <doc:CatalogAttribute/ExactSearchableOption/exactSearchableDisabled>
  public var exactSearchableOption: CatalogAttribute.ExactSearchableOption =
    CatalogAttribute.ExactSearchableOption()

  /// If RETRIEVABLE_ENABLED, attribute values are retrievable in the search
  /// results. If unset, the server behavior defaults to
  /// [RETRIEVABLE_DISABLED][google.cloud.retail.v2.CatalogAttribute.RetrievableOption.RETRIEVABLE_DISABLED].
  ///
  /// [google.cloud.retail.v2.CatalogAttribute.RetrievableOption.RETRIEVABLE_DISABLED]: <doc:CatalogAttribute/RetrievableOption/retrievableDisabled>
  public var retrievableOption: CatalogAttribute.RetrievableOption =
    CatalogAttribute.RetrievableOption()

  /// Contains facet options.
  public var facetConfig: CatalogAttribute.FacetConfig? = nil

  /// Initialize a new instance of `CatalogAttribute`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CatalogAttribute().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible options for the facet that corresponds to the current attribute
  /// config.
  public struct FacetConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// If you don't set the facet
    /// [SearchRequest.FacetSpec.FacetKey.intervals][google.cloud.retail.v2.SearchRequest.FacetSpec.FacetKey.intervals]
    /// in the request to a numerical attribute, then we use the computed
    /// intervals with rounded bounds obtained from all its product numerical
    /// attribute values. The computed intervals might not be ideal for some
    /// attributes. Therefore, we give you the option to overwrite them with the
    /// facet_intervals field. The maximum of facet intervals per
    /// [CatalogAttribute][google.cloud.retail.v2.CatalogAttribute] is 40. Each
    /// interval must have a lower bound or an upper bound. If both bounds are
    /// provided, then the lower bound must be smaller or equal than the upper
    /// bound.
    ///
    /// [google.cloud.retail.v2.CatalogAttribute]: <doc:CatalogAttribute>
    /// [google.cloud.retail.v2.SearchRequest.FacetSpec.FacetKey.intervals]: <doc:SearchRequest/FacetSpec/FacetKey/intervals>
    public var facetIntervals: [Interval] = []

    /// Each instance represents a list of attribute values to ignore as facet
    /// values for a specific time range. The maximum number of instances per
    /// [CatalogAttribute][google.cloud.retail.v2.CatalogAttribute] is 25.
    ///
    /// [google.cloud.retail.v2.CatalogAttribute]: <doc:CatalogAttribute>
    public var ignoredFacetValues: [CatalogAttribute.FacetConfig.IgnoredFacetValues] = []

    /// Each instance replaces a list of facet values by a merged facet
    /// value. If a facet value is not in any list, then it will stay the same.
    /// To avoid conflicts, only paths of length 1 are accepted. In other words,
    /// if "dark_blue" merged into "BLUE", then the latter can't merge into
    /// "blues" because this would create a path of length 2. The maximum number
    /// of instances of MergedFacetValue per
    /// [CatalogAttribute][google.cloud.retail.v2.CatalogAttribute] is 100. This
    /// feature is available only for textual custom attributes.
    ///
    /// [google.cloud.retail.v2.CatalogAttribute]: <doc:CatalogAttribute>
    public var mergedFacetValues: [CatalogAttribute.FacetConfig.MergedFacetValue] = []

    /// Use this field only if you want to merge a facet key into another facet
    /// key.
    public var mergedFacet: CatalogAttribute.FacetConfig.MergedFacet? = nil

    /// Set this field only if you want to rerank based on facet values engaged
    /// by the user for the current key. This option is only possible for custom
    /// facetable textual keys.
    public var rerankConfig: CatalogAttribute.FacetConfig.RerankConfig? = nil

    /// Initialize a new instance of `FacetConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FacetConfig().with { $0.facetIntervals = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// [Facet values][google.cloud.retail.v2.SearchResponse.Facet.values] to
    /// ignore on [facets][google.cloud.retail.v2.SearchResponse.Facet] during
    /// the specified time range for the given
    /// [SearchResponse.Facet.key][google.cloud.retail.v2.SearchResponse.Facet.key]
    /// attribute.
    ///
    /// [google.cloud.retail.v2.SearchResponse.Facet]: <doc:SearchResponse/Facet>
    /// [google.cloud.retail.v2.SearchResponse.Facet.key]: <doc:SearchResponse/Facet/key>
    /// [google.cloud.retail.v2.SearchResponse.Facet.values]: <doc:SearchResponse/Facet/values>
    public struct IgnoredFacetValues: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// List of facet values to ignore for the following time range. The facet
      /// values are the same as the attribute values. There is a limit of 10
      /// values per instance of IgnoredFacetValues. Each value can have at most
      /// 128 characters.
      public var values: [Swift.String] = []

      /// Time range for the current list of facet values to ignore.
      /// If multiple time ranges are specified for an facet value for the
      /// current attribute, consider all of them. If both are empty, ignore
      /// always. If start time and end time are set, then start time
      /// must be before end time.
      /// If start time is not empty and end time is empty, then will ignore
      /// these facet values after the start time.
      public var startTime: GoogleCloudWKT.Timestamp? = nil

      /// If start time is empty and end time is not empty, then ignore these
      /// facet values before end time.
      public var endTime: GoogleCloudWKT.Timestamp? = nil

      /// Initialize a new instance of `IgnoredFacetValues`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = IgnoredFacetValues().with { $0.values = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.retail.v2.CatalogAttribute.FacetConfig.IgnoredFacetValues"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Replaces a set of textual facet values by the same (possibly different)
    /// merged facet value. Each facet value should appear at most once as a
    /// value per [CatalogAttribute][google.cloud.retail.v2.CatalogAttribute].
    /// This feature is available only for textual custom attributes.
    ///
    /// [google.cloud.retail.v2.CatalogAttribute]: <doc:CatalogAttribute>
    public struct MergedFacetValue: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// All the facet values that are replaces by the same
      /// [merged_value][google.cloud.retail.v2.CatalogAttribute.FacetConfig.MergedFacetValue.merged_value]
      /// that follows. The maximum number of values per MergedFacetValue is 25.
      /// Each value can have up to 128 characters.
      ///
      /// [google.cloud.retail.v2.CatalogAttribute.FacetConfig.MergedFacetValue.merged_value]: <doc:CatalogAttribute/FacetConfig/MergedFacetValue/mergedValue>
      public var values: [Swift.String] = []

      /// All the previous values are replaced by this merged facet value.
      /// This merged_value must be non-empty and can have up to 128 characters.
      public var mergedValue: Swift.String = Swift.String()

      /// Initialize a new instance of `MergedFacetValue`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = MergedFacetValue().with { $0.values = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.retail.v2.CatalogAttribute.FacetConfig.MergedFacetValue"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// The current facet key (i.e. attribute config) maps into the
    /// [merged_facet_key][google.cloud.retail.v2.CatalogAttribute.FacetConfig.MergedFacet.merged_facet_key].
    /// A facet key can have at most one child. The current facet key and the
    /// merged facet key need both to be textual custom attributes or both
    /// numerical custom attributes (same type).
    ///
    /// [google.cloud.retail.v2.CatalogAttribute.FacetConfig.MergedFacet.merged_facet_key]: <doc:CatalogAttribute/FacetConfig/MergedFacet/mergedFacetKey>
    public struct MergedFacet: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// The merged facet key should be a valid facet key that is different than
      /// the facet key of the current catalog attribute. We refer this is
      /// merged facet key as the child of the current catalog attribute. This
      /// merged facet key can't be a parent of another facet key (i.e. no
      /// directed path of length 2). This merged facet key needs to be either a
      /// textual custom attribute or a numerical custom attribute.
      public var mergedFacetKey: Swift.String = Swift.String()

      /// Initialize a new instance of `MergedFacet`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = MergedFacet().with { $0.mergedFacetKey = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.retail.v2.CatalogAttribute.FacetConfig.MergedFacet"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Options to rerank based on facet values engaged by the user for the
    /// current key. That key needs to be a custom textual key and facetable.
    /// To use this control, you also need to pass all the facet keys engaged by
    /// the user in the request using the field [SearchRequest.FacetSpec]. In
    /// particular, if you don't pass the facet keys engaged that you want to
    /// rerank on, this control won't be effective. Moreover, to obtain better
    /// results, the facet values that you want to rerank on should be close to
    /// English (ideally made of words, underscores, and spaces).
    public struct RerankConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// If set to true, then we also rerank the dynamic facets based on the
      /// facet values engaged by the user for the current attribute key during
      /// serving.
      public var rerankFacet: Swift.Bool = Swift.Bool()

      /// If empty, rerank on all facet values for the current key. Otherwise,
      /// will rerank on the facet values from this list only.
      public var facetValues: [Swift.String] = []

      /// Initialize a new instance of `RerankConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = RerankConfig().with { $0.rerankFacet = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.retail.v2.CatalogAttribute.FacetConfig.RerankConfig"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.CatalogAttribute.FacetConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The type of an attribute.
  public enum AttributeType: Codable, Equatable, Sendable {
    /// The type of the attribute is unknown.
    ///
    /// Used when type cannot be derived from attribute that is not
    /// [in_use][google.cloud.retail.v2.CatalogAttribute.in_use].
    ///
    /// [google.cloud.retail.v2.CatalogAttribute.in_use]: <doc:CatalogAttribute/inUse>
    case unknown
    /// Textual attribute.
    case textual
    /// Numerical attribute.
    case numerical
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .textual: return 1
      case .numerical: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unknown: return "UNKNOWN"
      case .textual: return "TEXTUAL"
      case .numerical: return "NUMERICAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AttributeType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNKNOWN": self = .unknown
      case "TEXTUAL": self = .textual
      case "NUMERICAL": self = .numerical
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AttributeType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .textual
      case 2: self = .numerical
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode(0)
      case .textual: return try container.encode(1)
      case .numerical: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The status of the indexable option of a catalog attribute.
  public enum IndexableOption: Codable, Equatable, Sendable {
    /// Value used when unset.
    case unspecified
    /// Indexable option enabled for an attribute.
    case indexableEnabled
    /// Indexable option disabled for an attribute.
    case indexableDisabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .indexableEnabled: return 1
      case .indexableDisabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INDEXABLE_OPTION_UNSPECIFIED"
      case .indexableEnabled: return "INDEXABLE_ENABLED"
      case .indexableDisabled: return "INDEXABLE_DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:IndexableOption/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INDEXABLE_OPTION_UNSPECIFIED": self = .unspecified
      case "INDEXABLE_ENABLED": self = .indexableEnabled
      case "INDEXABLE_DISABLED": self = .indexableDisabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:IndexableOption/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .indexableEnabled
      case 2: self = .indexableDisabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .indexableEnabled: return try container.encode(1)
      case .indexableDisabled: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The status of the dynamic facetable option of a catalog attribute.
  public enum DynamicFacetableOption: Codable, Equatable, Sendable {
    /// Value used when unset.
    case unspecified
    /// Dynamic facetable option enabled for an attribute.
    case dynamicFacetableEnabled
    /// Dynamic facetable option disabled for an attribute.
    case dynamicFacetableDisabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .dynamicFacetableEnabled: return 1
      case .dynamicFacetableDisabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DYNAMIC_FACETABLE_OPTION_UNSPECIFIED"
      case .dynamicFacetableEnabled: return "DYNAMIC_FACETABLE_ENABLED"
      case .dynamicFacetableDisabled: return "DYNAMIC_FACETABLE_DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DynamicFacetableOption/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DYNAMIC_FACETABLE_OPTION_UNSPECIFIED": self = .unspecified
      case "DYNAMIC_FACETABLE_ENABLED": self = .dynamicFacetableEnabled
      case "DYNAMIC_FACETABLE_DISABLED": self = .dynamicFacetableDisabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DynamicFacetableOption/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .dynamicFacetableEnabled
      case 2: self = .dynamicFacetableDisabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .dynamicFacetableEnabled: return try container.encode(1)
      case .dynamicFacetableDisabled: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The status of the searchable option of a catalog attribute.
  public enum SearchableOption: Codable, Equatable, Sendable {
    /// Value used when unset.
    case unspecified
    /// Searchable option enabled for an attribute.
    case searchableEnabled
    /// Searchable option disabled for an attribute.
    case searchableDisabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .searchableEnabled: return 1
      case .searchableDisabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SEARCHABLE_OPTION_UNSPECIFIED"
      case .searchableEnabled: return "SEARCHABLE_ENABLED"
      case .searchableDisabled: return "SEARCHABLE_DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SearchableOption/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SEARCHABLE_OPTION_UNSPECIFIED": self = .unspecified
      case "SEARCHABLE_ENABLED": self = .searchableEnabled
      case "SEARCHABLE_DISABLED": self = .searchableDisabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SearchableOption/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .searchableEnabled
      case 2: self = .searchableDisabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .searchableEnabled: return try container.encode(1)
      case .searchableDisabled: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The status of the exact-searchable option of a catalog attribute.
  public enum ExactSearchableOption: Codable, Equatable, Sendable {
    /// Value used when unset.
    case unspecified
    /// Exact searchable option enabled for an attribute.
    case exactSearchableEnabled
    /// Exact searchable option disabled for an attribute.
    case exactSearchableDisabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .exactSearchableEnabled: return 1
      case .exactSearchableDisabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EXACT_SEARCHABLE_OPTION_UNSPECIFIED"
      case .exactSearchableEnabled: return "EXACT_SEARCHABLE_ENABLED"
      case .exactSearchableDisabled: return "EXACT_SEARCHABLE_DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ExactSearchableOption/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EXACT_SEARCHABLE_OPTION_UNSPECIFIED": self = .unspecified
      case "EXACT_SEARCHABLE_ENABLED": self = .exactSearchableEnabled
      case "EXACT_SEARCHABLE_DISABLED": self = .exactSearchableDisabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ExactSearchableOption/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .exactSearchableEnabled
      case 2: self = .exactSearchableDisabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .exactSearchableEnabled: return try container.encode(1)
      case .exactSearchableDisabled: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The status of the retrievable option of a catalog attribute.
  public enum RetrievableOption: Codable, Equatable, Sendable {
    /// Value used when unset.
    case unspecified
    /// Retrievable option enabled for an attribute.
    case retrievableEnabled
    /// Retrievable option disabled for an attribute.
    case retrievableDisabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .retrievableEnabled: return 1
      case .retrievableDisabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RETRIEVABLE_OPTION_UNSPECIFIED"
      case .retrievableEnabled: return "RETRIEVABLE_ENABLED"
      case .retrievableDisabled: return "RETRIEVABLE_DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RetrievableOption/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RETRIEVABLE_OPTION_UNSPECIFIED": self = .unspecified
      case "RETRIEVABLE_ENABLED": self = .retrievableEnabled
      case "RETRIEVABLE_DISABLED": self = .retrievableDisabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RetrievableOption/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .retrievableEnabled
      case 2: self = .retrievableDisabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .retrievableEnabled: return try container.encode(1)
      case .retrievableDisabled: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.CatalogAttribute"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
