// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for CollectUserEvent method.
public struct CollectUserEventRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent catalog name, such as
  /// `projects/1234/locations/global/catalogs/default_catalog`.
  public var parent: Swift.String = Swift.String()

  /// Required. URL encoded UserEvent proto with a length limit of 2,000,000
  /// characters.
  public var userEvent: Swift.String = Swift.String()

  /// The URL including cgi-parameters but excluding the hash fragment with a
  /// length limit of 5,000 characters. This is often more useful than the
  /// referer URL, because many browsers only send the domain for 3rd party
  /// requests.
  public var uri: Swift.String = Swift.String()

  /// The event timestamp in milliseconds. This prevents browser caching of
  /// otherwise identical get requests. The name is abbreviated to reduce the
  /// payload bytes.
  public var ets: Swift.Int64 = Swift.Int64()

  /// An arbitrary serialized JSON string that contains necessary information
  /// that can comprise a user event. When this field is specified, the
  /// user_event field will be ignored. Note: line-delimited JSON is not
  /// supported, a single JSON only.
  public var rawJson: Swift.String = Swift.String()

  /// The rule that can convert the raw_json to a user event. It is needed
  /// only when the raw_json is set.
  public var conversionRule: OneOf_ConversionRule? = nil

  /// Initialize a new instance of `CollectUserEventRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CollectUserEventRequest().with { $0.prebuiltRule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case prebuiltRule = "prebuiltRule"
    case parent = "parent"
    case userEvent = "userEvent"
    case uri = "uri"
    case ets = "ets"
    case rawJson = "rawJson"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.userEvent = try container.decode(Swift.String.self, forKey: .userEvent)
    self.uri = try container.decode(Swift.String.self, forKey: .uri)
    self.ets = try container.decode(Swift.Int64.self, forKey: .ets)
    self.rawJson = try container.decode(Swift.String.self, forKey: .rawJson)

    var conversionRule: OneOf_ConversionRule? = nil
    let conversionRuleCheckAndSet = {
      if conversionRule != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'conversionRule'"))
      }
      conversionRule = $0
    }
    if let prebuiltRule = try container.decodeIfPresent(Swift.String.self, forKey: .prebuiltRule) {
      try conversionRuleCheckAndSet(.prebuiltRule(prebuiltRule))
    }
    self.conversionRule = conversionRule
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.userEvent, forKey: .userEvent)
    try container.encode(self.uri, forKey: .uri)
    try container.encode(self.ets, forKey: .ets)
    try container.encode(self.rawJson, forKey: .rawJson)

    if let choice = self.conversionRule {
      switch choice {
      case .prebuiltRule(let value):
        try container.encode(value, forKey: .prebuiltRule)
      }
    }
  }

  /// The rule that can convert the raw_json to a user event. It is needed
  /// only when the raw_json is set.
  public enum OneOf_ConversionRule: Codable, Equatable, Sendable {
    /// The prebuilt rule name that can convert a specific type of raw_json.
    /// For example: "ga4_bq" rule for the GA4 user event schema.
    case prebuiltRule(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.CollectUserEventRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
