// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Catalog level autocomplete config for customers to customize autocomplete
/// feature's settings.
public struct CompletionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Immutable. Fully qualified name
  /// `projects/*/locations/*/catalogs/*/completionConfig`
  public var name: Swift.String = Swift.String()

  /// Specifies the matching order for autocomplete suggestions, e.g., a query
  /// consisting of 'sh' with 'out-of-order' specified would suggest "women's
  /// shoes", whereas a query of 'red s' with 'exact-prefix' specified would
  /// suggest "red shoes". Currently supported values:
  ///
  /// * 'out-of-order'
  /// * 'exact-prefix'
  ///
  /// Default value: 'exact-prefix'.
  public var matchingOrder: Swift.String = Swift.String()

  /// The maximum number of autocomplete suggestions returned per term. Default
  /// value is 20. If left unset or set to 0, then will fallback to default
  /// value.
  ///
  /// Value range is 1 to 20.
  public var maxSuggestions: Swift.Int32 = Swift.Int32()

  /// The minimum number of characters needed to be typed in order to get
  /// suggestions. Default value is 2. If left unset or set to 0, then will
  /// fallback to default value.
  ///
  /// Value range is 1 to 20.
  public var minPrefixLength: Swift.Int32 = Swift.Int32()

  /// If set to true, the auto learning function is enabled. Auto learning uses
  /// user data to generate suggestions using ML techniques. Default value is
  /// false. Only after enabling auto learning can users use `cloud-retail`
  /// data in
  /// [CompleteQueryRequest][google.cloud.retail.v2.CompleteQueryRequest].
  ///
  /// [google.cloud.retail.v2.CompleteQueryRequest]: <doc:CompleteQueryRequest>
  public var autoLearning: Swift.Bool = Swift.Bool()

  /// Output only. The source data for the latest import of the autocomplete
  /// suggestion phrases.
  public var suggestionsInputConfig: CompletionDataInputConfig? = nil

  /// Output only. Name of the LRO corresponding to the latest suggestion terms
  /// list import.
  ///
  /// Can use [GetOperation][google.longrunning.Operations.GetOperation] API
  /// method to retrieve the latest state of the Long Running Operation.
  public var lastSuggestionsImportOperation: Swift.String = Swift.String()

  /// Output only. The source data for the latest import of the autocomplete
  /// denylist phrases.
  public var denylistInputConfig: CompletionDataInputConfig? = nil

  /// Output only. Name of the LRO corresponding to the latest denylist import.
  ///
  /// Can use [GetOperation][google.longrunning.Operations.GetOperation] API to
  /// retrieve the latest state of the Long Running Operation.
  public var lastDenylistImportOperation: Swift.String = Swift.String()

  /// Output only. The source data for the latest import of the autocomplete
  /// allowlist phrases.
  public var allowlistInputConfig: CompletionDataInputConfig? = nil

  /// Output only. Name of the LRO corresponding to the latest allowlist import.
  ///
  /// Can use [GetOperation][google.longrunning.Operations.GetOperation] API to
  /// retrieve the latest state of the Long Running Operation.
  public var lastAllowlistImportOperation: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CompletionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CompletionConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let matchingOrder = CodingKeys(stringValue: "matchingOrder")
    static let maxSuggestions = CodingKeys(stringValue: "maxSuggestions")
    static let minPrefixLength = CodingKeys(stringValue: "minPrefixLength")
    static let autoLearning = CodingKeys(stringValue: "autoLearning")
    static let suggestionsInputConfig = CodingKeys(stringValue: "suggestionsInputConfig")
    static let lastSuggestionsImportOperation = CodingKeys(
      stringValue: "lastSuggestionsImportOperation")
    static let denylistInputConfig = CodingKeys(stringValue: "denylistInputConfig")
    static let lastDenylistImportOperation = CodingKeys(stringValue: "lastDenylistImportOperation")
    static let allowlistInputConfig = CodingKeys(stringValue: "allowlistInputConfig")
    static let lastAllowlistImportOperation = CodingKeys(
      stringValue: "lastAllowlistImportOperation")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "matchingOrder",
      "maxSuggestions",
      "minPrefixLength",
      "autoLearning",
      "suggestionsInputConfig",
      "lastSuggestionsImportOperation",
      "denylistInputConfig",
      "lastDenylistImportOperation",
      "allowlistInputConfig",
      "lastAllowlistImportOperation",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .matchingOrder) {
      self.matchingOrder = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxSuggestions) {
      self.maxSuggestions = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minPrefixLength) {
      self.minPrefixLength = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .autoLearning) {
      self.autoLearning = value
    }
    self.suggestionsInputConfig = try container.decodeIfPresent(
      CompletionDataInputConfig.self, forKey: .suggestionsInputConfig)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .lastSuggestionsImportOperation)
    {
      self.lastSuggestionsImportOperation = value
    }
    self.denylistInputConfig = try container.decodeIfPresent(
      CompletionDataInputConfig.self, forKey: .denylistInputConfig)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .lastDenylistImportOperation)
    {
      self.lastDenylistImportOperation = value
    }
    self.allowlistInputConfig = try container.decodeIfPresent(
      CompletionDataInputConfig.self, forKey: .allowlistInputConfig)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .lastAllowlistImportOperation)
    {
      self.lastAllowlistImportOperation = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.matchingOrder, forKey: .matchingOrder)
    try container.encode(self.maxSuggestions, forKey: .maxSuggestions)
    try container.encode(self.minPrefixLength, forKey: .minPrefixLength)
    try container.encode(self.autoLearning, forKey: .autoLearning)
    try container.encodeIfPresent(self.suggestionsInputConfig, forKey: .suggestionsInputConfig)
    try container.encode(
      self.lastSuggestionsImportOperation, forKey: .lastSuggestionsImportOperation)
    try container.encodeIfPresent(self.denylistInputConfig, forKey: .denylistInputConfig)
    try container.encode(self.lastDenylistImportOperation, forKey: .lastDenylistImportOperation)
    try container.encodeIfPresent(self.allowlistInputConfig, forKey: .allowlistInputConfig)
    try container.encode(self.lastAllowlistImportOperation, forKey: .lastAllowlistImportOperation)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.CompletionConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
