// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Response of the autocomplete query.
public struct CompleteQueryResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Results of the matching suggestions. The result list is ordered and the
  /// first result is top suggestion.
  public var completionResults: [CompleteQueryResponse.CompletionResult] = []

  /// A unique complete token. This should be included in the
  /// [UserEvent.completion_detail][google.cloud.retail.v2.UserEvent.completion_detail]
  /// for search events resulting from this completion, which enables accurate
  /// attribution of complete model performance.
  ///
  /// [google.cloud.retail.v2.UserEvent.completion_detail]: <doc:UserEvent/completionDetail>
  public var attributionToken: Swift.String = Swift.String()

  /// Deprecated. Matched recent searches of this user. The maximum number of
  /// recent searches is 10. This field is a restricted feature. If you want to
  /// enable it, contact Retail Search support.
  ///
  /// This feature is only available when
  /// [CompleteQueryRequest.visitor_id][google.cloud.retail.v2.CompleteQueryRequest.visitor_id]
  /// field is set and [UserEvent][google.cloud.retail.v2.UserEvent] is imported.
  /// The recent searches satisfy the follow rules:
  ///
  ///  * They are ordered from latest to oldest.
  ///
  ///  * They are matched with
  ///  [CompleteQueryRequest.query][google.cloud.retail.v2.CompleteQueryRequest.query]
  ///  case insensitively.
  ///
  ///  * They are transformed to lower case.
  ///
  ///  * They are UTF-8 safe.
  ///
  /// Recent searches are deduplicated. More recent searches will be reserved
  /// when duplication happens.
  ///
  /// [google.cloud.retail.v2.CompleteQueryRequest.query]: <doc:CompleteQueryRequest/query>
  /// [google.cloud.retail.v2.CompleteQueryRequest.visitor_id]: <doc:CompleteQueryRequest/visitorId>
  /// [google.cloud.retail.v2.UserEvent]: <doc:UserEvent>
  @available(*, deprecated)
  public var recentSearchResults: [CompleteQueryResponse.RecentSearchResult] = []

  /// A map of matched attribute suggestions. This field is only available for
  /// `cloud-retail` dataset.
  ///
  /// Current supported keys:
  ///
  /// * `brands`
  ///
  /// * `categories`
  public var attributeResults: [Swift.String: CompleteQueryResponse.AttributeResult] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CompleteQueryResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CompleteQueryResponse().with { $0.completionResults = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let completionResults = CodingKeys(stringValue: "completionResults")
    static let attributionToken = CodingKeys(stringValue: "attributionToken")
    static let recentSearchResults = CodingKeys(stringValue: "recentSearchResults")
    static let attributeResults = CodingKeys(stringValue: "attributeResults")

    static let _knownKeys: Set<Swift.String> = [
      "completionResults",
      "attributionToken",
      "recentSearchResults",
      "attributeResults",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [CompleteQueryResponse.CompletionResult].self, forKey: .completionResults)
    {
      self.completionResults = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .attributionToken) {
      self.attributionToken = value
    }
    if let value = try container.decodeIfPresent(
      [CompleteQueryResponse.RecentSearchResult].self, forKey: .recentSearchResults)
    {
      self.recentSearchResults = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: CompleteQueryResponse.AttributeResult].self, forKey: .attributeResults)
    {
      self.attributeResults = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.completionResults, forKey: .completionResults)
    try container.encode(self.attributionToken, forKey: .attributionToken)
    try container.encode(self.recentSearchResults, forKey: .recentSearchResults)
    try container.encode(self.attributeResults, forKey: .attributeResults)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Resource that represents completion results.
  public struct CompletionResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The suggestion for the query.
    public var suggestion: Swift.String = Swift.String()

    /// Custom attributes for the suggestion term.
    ///
    /// * For `user-data`, the attributes are additional custom attributes
    /// ingested through BigQuery.
    ///
    /// * For `cloud-retail`, the attributes are product attributes generated
    /// by Cloud Retail. It requires
    /// [UserEvent.product_details][google.cloud.retail.v2.UserEvent.product_details]
    /// is imported properly.
    ///
    /// [google.cloud.retail.v2.UserEvent.product_details]: <doc:UserEvent/productDetails>
    public var attributes: [Swift.String: CustomAttribute] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CompletionResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CompletionResult().with { $0.suggestion = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let suggestion = CodingKeys(stringValue: "suggestion")
      static let attributes = CodingKeys(stringValue: "attributes")

      static let _knownKeys: Set<Swift.String> = [
        "suggestion",
        "attributes",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .suggestion) {
        self.suggestion = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: CustomAttribute].self, forKey: .attributes)
      {
        self.attributes = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.suggestion, forKey: .suggestion)
      try container.encode(self.attributes, forKey: .attributes)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.CompleteQueryResponse.CompletionResult"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Deprecated: Recent search of this user.
  @available(*, deprecated)
  public struct RecentSearchResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The recent search query.
    public var recentSearch: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RecentSearchResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RecentSearchResult().with { $0.recentSearch = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let recentSearch = CodingKeys(stringValue: "recentSearch")

      static let _knownKeys: Set<Swift.String> = [
        "recentSearch"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .recentSearch) {
        self.recentSearch = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.recentSearch, forKey: .recentSearch)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.CompleteQueryResponse.RecentSearchResult"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Resource that represents attribute results.
  public struct AttributeResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The list of suggestions for the attribute.
    public var suggestions: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AttributeResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AttributeResult().with { $0.suggestions = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let suggestions = CodingKeys(stringValue: "suggestions")

      static let _knownKeys: Set<Swift.String> = [
        "suggestions"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .suggestions) {
        self.suggestions = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.suggestions, forKey: .suggestions)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.CompleteQueryResponse.AttributeResult"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.CompleteQueryResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
