// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax

/// Service for modifying Control.
///
/// @Snippet(path: "ControlServiceQuickstart")
public class ControlServiceClient: Clients.ControlServiceProtocol {
  let inner: any Clients.ControlServiceStub

  /// Creates a new `ControlServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ControlServiceStub = try Clients.ControlServiceTransport(options)
    inner = Clients.ControlServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ControlServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a Control.
  ///
  /// If the [Control][google.cloud.retail.v2.Control] to create already exists,
  /// an ALREADY_EXISTS error is returned.
  ///
  /// [google.cloud.retail.v2.Control]: <doc:Control>
  ///
  /// @Snippet(path: "ControlService_CreateControl")
  public func createControl(
    request: CreateControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRetailV2.Control {
    try await self.inner.createControl(request: request, options: options)
  }

  /// Deletes a Control.
  ///
  /// If the [Control][google.cloud.retail.v2.Control] to delete does not exist,
  /// a NOT_FOUND error is returned.
  ///
  /// [google.cloud.retail.v2.Control]: <doc:Control>
  ///
  /// @Snippet(path: "ControlService_DeleteControl")
  public func deleteControl(
    request: DeleteControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteControl(request: request, options: options)
  }

  /// Updates a Control.
  ///
  /// [Control][google.cloud.retail.v2.Control] cannot be set to a different
  /// oneof field, if so an INVALID_ARGUMENT is returned. If the
  /// [Control][google.cloud.retail.v2.Control] to update does not exist, a
  /// NOT_FOUND error is returned.
  ///
  /// [google.cloud.retail.v2.Control]: <doc:Control>
  ///
  /// @Snippet(path: "ControlService_UpdateControl")
  public func updateControl(
    request: UpdateControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRetailV2.Control {
    try await self.inner.updateControl(request: request, options: options)
  }

  /// Gets a Control.
  ///
  /// @Snippet(path: "ControlService_GetControl")
  public func getControl(
    request: GetControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRetailV2.Control {
    try await self.inner.getControl(request: request, options: options)
  }

  /// Lists all Controls by their parent
  /// [Catalog][google.cloud.retail.v2.Catalog].
  ///
  /// [google.cloud.retail.v2.Catalog]: <doc:Catalog>
  ///
  /// @Snippet(path: "ControlService_ListControls")
  public func listControls(
    request: ListControlsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRetailV2.ListControlsResponse {
    try await self.inner.listControls(request: request, options: options)
  }

  /// Lists all Controls by their parent
  /// [Catalog][google.cloud.retail.v2.Catalog].
  ///
  /// [google.cloud.retail.v2.Catalog]: <doc:Catalog>
  ///
  /// @Snippet(path: "ControlService_ListControls")
  public func listControls(
    byItem: ListControlsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRetailV2.ListControlsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listControls(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ControlService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ControlService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ControlService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ControlServiceClient`.
  ///
  /// To mock `ControlServiceClient` change your functions to receive
  /// `some ControlServiceProtocol` or `any ControlServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ControlServiceProtocol {
    /// See `ControlServiceClient.createControl`.
    func createControl(request: CreateControlRequest) async throws -> GoogleCloudRetailV2.Control

    /// See `ControlServiceClient.createControl`.
    func createControl(
      parent: Swift.String,
      control: Control?,
      controlId: Swift.String,
    ) async throws -> GoogleCloudRetailV2.Control

    /// See `ControlServiceClient.deleteControl`.
    func deleteControl(request: DeleteControlRequest) async throws

    /// See `ControlServiceClient.deleteControl`.
    func deleteControl(
      name: Swift.String,
    ) async throws

    /// See `ControlServiceClient.updateControl`.
    func updateControl(request: UpdateControlRequest) async throws -> GoogleCloudRetailV2.Control

    /// See `ControlServiceClient.updateControl`.
    func updateControl(
      control: Control?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudRetailV2.Control

    /// See `ControlServiceClient.getControl`.
    func getControl(request: GetControlRequest) async throws -> GoogleCloudRetailV2.Control

    /// See `ControlServiceClient.getControl`.
    func getControl(
      name: Swift.String,
    ) async throws -> GoogleCloudRetailV2.Control

    /// See `ControlServiceClient.listControls`.
    func listControls(request: ListControlsRequest) async throws
      -> GoogleCloudRetailV2.ListControlsResponse

    /// See `ControlServiceClient.listControls`.
    func listControls(
      byItem: ListControlsRequest
    ) throws -> any AsyncSequence<Control, Swift.Error>

    /// See `ControlServiceClient.listControls`.
    func listControls(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Control, Swift.Error>

    /// See `ControlServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `ControlServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ControlServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ControlServiceClient.createControl`.
    func createControl(
      request: CreateControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.Control

    /// See `ControlServiceClient.deleteControl`.
    func deleteControl(
      request: DeleteControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ControlServiceClient.updateControl`.
    func updateControl(
      request: UpdateControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.Control

    /// See `ControlServiceClient.getControl`.
    func getControl(
      request: GetControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.Control

    /// See `ControlServiceClient.listControls`.
    func listControls(
      request: ListControlsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.ListControlsResponse

    /// See `ControlServiceClient.listControls`.
    func listControls(
      byItem: ListControlsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Control, Swift.Error>

    /// See `ControlServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ControlServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>
  }
}

// Default implementations
extension Clients.ControlServiceProtocol {
  public func createControl(request: CreateControlRequest) async throws
    -> GoogleCloudRetailV2.Control
  {
    try await self.createControl(request: request, options: .init())
  }

  public func createControl(
    request: CreateControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRetailV2.Control {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createControl(
    parent: Swift.String,
    control: Control?,
    controlId: Swift.String,
  ) async throws -> GoogleCloudRetailV2.Control {
    let request = CreateControlRequest().with {
      $0.parent = parent
      $0.control = control
      $0.controlId = controlId
    }
    return try await self.createControl(request: request)
  }

  public func deleteControl(request: DeleteControlRequest) async throws {
    try await self.deleteControl(request: request, options: .init())
  }

  public func deleteControl(
    request: DeleteControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteControl(
    name: Swift.String,
  ) async throws {
    let request = DeleteControlRequest().with {
      $0.name = name
    }
    try await self.deleteControl(request: request)
  }

  public func updateControl(request: UpdateControlRequest) async throws
    -> GoogleCloudRetailV2.Control
  {
    try await self.updateControl(request: request, options: .init())
  }

  public func updateControl(
    request: UpdateControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRetailV2.Control {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateControl(
    control: Control?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudRetailV2.Control {
    let request = UpdateControlRequest().with {
      $0.control = control
      $0.updateMask = updateMask
    }
    return try await self.updateControl(request: request)
  }

  public func getControl(request: GetControlRequest) async throws -> GoogleCloudRetailV2.Control {
    try await self.getControl(request: request, options: .init())
  }

  public func getControl(
    request: GetControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRetailV2.Control {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getControl(
    name: Swift.String,
  ) async throws -> GoogleCloudRetailV2.Control {
    let request = GetControlRequest().with {
      $0.name = name
    }
    return try await self.getControl(request: request)
  }

  public func listControls(request: ListControlsRequest) async throws
    -> GoogleCloudRetailV2.ListControlsResponse
  {
    try await self.listControls(request: request, options: .init())
  }

  public func listControls(
    request: ListControlsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRetailV2.ListControlsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listControls(
    byItem: ListControlsRequest
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    try self.listControls(byItem: byItem, options: .init())
  }

  public func listControls(
    byItem: ListControlsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRetailV2.ListControlsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listControls(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    let request = ListControlsRequest().with {
      $0.parent = parent
    }
    return try self.listControls(byItem: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
