// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for
/// [ConversationalSearchService.ConversationalSearch][google.cloud.retail.v2.ConversationalSearchService.ConversationalSearch]
/// method.
///
/// [google.cloud.retail.v2.ConversationalSearchService.ConversationalSearch]: <doc:ConversationalSearchServiceClient/conversationalSearch(request:options:)>
public struct ConversationalSearchResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The types Retail classifies the search query as.
  ///
  /// Supported values are:
  ///
  /// - "ORDER_SUPPORT"
  /// - "SIMPLE_PRODUCT_SEARCH"
  /// - "INTENT_REFINEMENT"
  /// - "PRODUCT_DETAILS"
  /// - "PRODUCT_COMPARISON"
  /// - "DEALS_AND_COUPONS"
  /// - "STORE_RELEVANT"
  /// - "BLOCKLISTED"
  /// - "BEST_PRODUCT"
  /// - "RETAIL_SUPPORT"
  /// - "DISABLED"
  public var userQueryTypes: [Swift.String] = []

  /// The conversational answer-based text response generated by the Server.
  public var conversationalTextResponse: Swift.String = Swift.String()

  /// The conversational followup question generated for Intent refinement.
  public var followupQuestion: ConversationalSearchResponse.FollowupQuestion? = nil

  /// Conversation UUID. This field will be stored in client side storage to
  /// maintain the conversation session with server and will be used for next
  /// search request's
  /// [ConversationalSearchRequest.conversation_id][google.cloud.retail.v2.ConversationalSearchRequest.conversation_id]
  /// to restore conversation state in server.
  ///
  /// [google.cloud.retail.v2.ConversationalSearchRequest.conversation_id]: <doc:ConversationalSearchRequest/conversationId>
  public var conversationId: Swift.String = Swift.String()

  /// The proposed refined search queries. They can be used to fetch the relevant
  /// search results. When using CONVERSATIONAL_FILTER_ONLY mode, the
  /// refined_query from search response will be populated here.
  public var refinedSearch: [ConversationalSearchResponse.RefinedSearch] = []

  /// This field specifies all related information that is needed on client
  /// side for UI rendering of conversational filtering search.
  public var conversationalFilteringResult:
    ConversationalSearchResponse.ConversationalFilteringResult? = nil

  /// Output only. The state of the response generation.
  public var state: ConversationalSearchResponse.State = ConversationalSearchResponse.State()

  /// Initialize a new instance of `ConversationalSearchResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConversationalSearchResponse().with { $0.userQueryTypes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The conversational followup question generated for Intent refinement.
  public struct FollowupQuestion: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The conversational followup question generated for Intent refinement.
    public var followupQuestion: Swift.String = Swift.String()

    /// The answer options provided to client for the follow-up question.
    public var suggestedAnswers: [ConversationalSearchResponse.FollowupQuestion.SuggestedAnswer] =
      []

    /// Initialize a new instance of `FollowupQuestion`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FollowupQuestion().with { $0.followupQuestion = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Suggested answers to the follow-up question.
    /// If it's numerical attribute, only ProductAttributeInterval will be set.
    /// If it's textual attribute, only productAttributeValue will be set.
    public struct SuggestedAnswer: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Product attribute value, including an attribute key and an
      /// attribute value. Other types can be added here in the future.
      public var productAttributeValue: ProductAttributeValue? = nil

      /// Initialize a new instance of `SuggestedAnswer`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SuggestedAnswer().with { $0.productAttributeValue = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.retail.v2.ConversationalSearchResponse.FollowupQuestion.SuggestedAnswer"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.retail.v2.ConversationalSearchResponse.FollowupQuestion"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The proposed refined search for intent-refinement/bundled shopping
  /// conversation. When using CONVERSATIONAL_FILTER_ONLY mode, the
  /// refined_query from search response will be populated here.
  public struct RefinedSearch: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The query to be used for search.
    public var query: Swift.String = Swift.String()

    /// Initialize a new instance of `RefinedSearch`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RefinedSearch().with { $0.query = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.ConversationalSearchResponse.RefinedSearch"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// This field specifies all related information that is needed on client
  /// side for UI rendering of conversational filtering search.
  public struct ConversationalFilteringResult: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The conversational filtering question.
    public var followupQuestion: ConversationalSearchResponse.FollowupQuestion? = nil

    /// This is the incremental additional filters implied from the current
    /// user answer. User should add the suggested addition filters to the
    /// previous [ConversationalSearchRequest.search_params.filter][] and
    /// [SearchRequest.filter][google.cloud.retail.v2.SearchRequest.filter],  and
    /// use the merged filter in the follow up requests.
    public var additionalFilter:
      ConversationalSearchResponse.ConversationalFilteringResult.AdditionalFilter? = nil

    /// Initialize a new instance of `ConversationalFilteringResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConversationalFilteringResult().with { $0.followupQuestion = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Additional filter that client side need to apply.
    public struct AdditionalFilter: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Product attribute value, including an attribute key and an
      /// attribute value. Other types can be added here in the future.
      public var productAttributeValue: ProductAttributeValue? = nil

      /// Initialize a new instance of `AdditionalFilter`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = AdditionalFilter().with { $0.productAttributeValue = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.retail.v2.ConversationalSearchResponse.ConversationalFilteringResult.AdditionalFilter"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.retail.v2.ConversationalSearchResponse.ConversationalFilteringResult"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The state of the response generation.
  public enum State: Codable, Equatable, Sendable {
    /// Unknown.
    case unspecified
    /// Response generation is being streamed.
    case streaming
    /// Response generation has succeeded.
    case succeeded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .streaming: return 1
      case .succeeded: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .streaming: return "STREAMING"
      case .succeeded: return "SUCCEEDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "STREAMING": self = .streaming
      case "SUCCEEDED": self = .succeeded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .streaming
      case 2: self = .succeeded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .streaming: return try container.encode(1)
      case .succeeded: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.ConversationalSearchResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
