// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ProductService.DeleteProduct][google.cloud.retail.v2.ProductService.DeleteProduct]
/// method.
///
/// [google.cloud.retail.v2.ProductService.DeleteProduct]: <doc:ProductService/deleteProduct(request:)>
public struct DeleteProductRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Full resource name of [Product][google.cloud.retail.v2.Product],
  /// such as
  /// `projects/*/locations/global/catalogs/default_catalog/branches/default_branch/products/some_product_id`.
  ///
  /// If the caller does not have permission to delete the
  /// [Product][google.cloud.retail.v2.Product], regardless of whether or not it
  /// exists, a PERMISSION_DENIED error is returned.
  ///
  /// If the [Product][google.cloud.retail.v2.Product] to delete does not exist,
  /// a NOT_FOUND error is returned.
  ///
  /// The [Product][google.cloud.retail.v2.Product] to delete can neither be a
  /// [Product.Type.COLLECTION][google.cloud.retail.v2.Product.Type.COLLECTION]
  /// [Product][google.cloud.retail.v2.Product] member nor a
  /// [Product.Type.PRIMARY][google.cloud.retail.v2.Product.Type.PRIMARY]
  /// [Product][google.cloud.retail.v2.Product] with more than one
  /// [variants][google.cloud.retail.v2.Product.Type.VARIANT]. Otherwise, an
  /// INVALID_ARGUMENT error is returned.
  ///
  /// All inventory information for the named
  /// [Product][google.cloud.retail.v2.Product] will be deleted.
  ///
  /// [google.cloud.retail.v2.Product]: <doc:Product>
  /// [google.cloud.retail.v2.Product.Type.COLLECTION]: <doc:Product/Type_/collection>
  /// [google.cloud.retail.v2.Product.Type.PRIMARY]: <doc:Product/Type_/primary>
  /// [google.cloud.retail.v2.Product.Type.VARIANT]: <doc:Product/Type_/variant>
  public var name: Swift.String = Swift.String()

  /// Initialize a new instance of `DeleteProductRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteProductRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.DeleteProductRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
