// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Metadata for active A/B testing experiment.
public struct ExperimentInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The fully qualified resource name of the experiment that provides the
  /// serving config under test, should an active experiment exist. For example:
  /// `projects/*/locations/global/catalogs/default_catalog/experiments/experiment_id`
  public var experiment: Swift.String = Swift.String()

  /// Information associated with the specific experiment entity being recorded.
  public var experimentMetadata: OneOf_ExperimentMetadata? = nil

  /// Initialize a new instance of `ExperimentInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExperimentInfo().with { $0.servingConfigExperiment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case servingConfigExperiment = "servingConfigExperiment"
    case experiment = "experiment"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.experiment = try container.decode(Swift.String.self, forKey: .experiment)

    var experimentMetadata: OneOf_ExperimentMetadata? = nil
    let experimentMetadataCheckAndSet = {
      if experimentMetadata != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'experimentMetadata'"))
      }
      experimentMetadata = $0
    }
    if let servingConfigExperiment = try container.decodeIfPresent(
      ExperimentInfo.ServingConfigExperiment?.self, forKey: .servingConfigExperiment)
    {
      try experimentMetadataCheckAndSet(.servingConfigExperiment(servingConfigExperiment))
    }
    self.experimentMetadata = experimentMetadata
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.experiment, forKey: .experiment)

    if let choice = self.experimentMetadata {
      switch choice {
      case .servingConfigExperiment(let value):
        try container.encode(value, forKey: .servingConfigExperiment)
      }
    }
  }

  /// Metadata for active serving config A/B tests.
  public struct ServingConfigExperiment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The fully qualified resource name of the original
    /// [SearchRequest.placement][google.cloud.retail.v2.SearchRequest.placement]
    /// in the search request prior to reassignment by experiment API. For
    /// example: `projects/*/locations/*/catalogs/*/servingConfigs/*`.
    ///
    /// [google.cloud.retail.v2.SearchRequest.placement]: <doc:SearchRequest/placement>
    public var originalServingConfig: Swift.String = Swift.String()

    /// The fully qualified resource name of the serving config
    /// `Experiment.VariantArm.serving_config_id` responsible for generating
    /// the search response. For example:
    /// `projects/*/locations/*/catalogs/*/servingConfigs/*`.
    public var experimentServingConfig: Swift.String = Swift.String()

    /// Initialize a new instance of `ServingConfigExperiment`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ServingConfigExperiment().with { $0.originalServingConfig = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.ExperimentInfo.ServingConfigExperiment"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Information associated with the specific experiment entity being recorded.
  public enum OneOf_ExperimentMetadata: Codable, Equatable, Sendable {
    /// A/B test between existing Cloud Retail Search
    /// [ServingConfig][google.cloud.retail.v2.ServingConfig]s.
    ///
    /// [google.cloud.retail.v2.ServingConfig]: <doc:ServingConfig>
    indirect case servingConfigExperiment(ExperimentInfo.ServingConfigExperiment?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.ExperimentInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
