// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Fulfillment information, such as the store IDs for in-store pickup or region
/// IDs for different shipping methods.
public struct FulfillmentInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The fulfillment type, including commonly used types (such as pickup in
  /// store and same day delivery), and custom types. Customers have to map
  /// custom types to their display names before rendering UI.
  ///
  /// Supported values:
  ///
  /// * "pickup-in-store"
  /// * "ship-to-store"
  /// * "same-day-delivery"
  /// * "next-day-delivery"
  /// * "custom-type-1"
  /// * "custom-type-2"
  /// * "custom-type-3"
  /// * "custom-type-4"
  /// * "custom-type-5"
  ///
  /// If this field is set to an invalid value other than these, an
  /// INVALID_ARGUMENT error is returned.
  public var type: Swift.String = Swift.String()

  /// The IDs for this [type][google.cloud.retail.v2.FulfillmentInfo.type], such
  /// as the store IDs for
  /// [FulfillmentInfo.type.pickup-in-store][google.cloud.retail.v2.FulfillmentInfo.type]
  /// or the region IDs for
  /// [FulfillmentInfo.type.same-day-delivery][google.cloud.retail.v2.FulfillmentInfo.type].
  ///
  /// A maximum of 3000 values are allowed. Each value must be a string with a
  /// length limit of 30 characters, matching the pattern `[a-zA-Z0-9_-]+`, such
  /// as "store1" or "REGION-2". Otherwise, an INVALID_ARGUMENT error is
  /// returned.
  ///
  /// [google.cloud.retail.v2.FulfillmentInfo.type]: <doc:FulfillmentInfo/type>
  public var placeIds: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FulfillmentInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FulfillmentInfo().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")
    static let placeIds = CodingKeys(stringValue: "placeIds")

    static let _knownKeys: Set<Swift.String> = [
      "type",
      "placeIds",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .placeIds) {
      self.placeIds = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.placeIds, forKey: .placeIds)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.FulfillmentInfo"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
