// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class GenerativeQuestionServiceLogging: GenerativeQuestionServiceStub {
    let inner: any GenerativeQuestionServiceStub
    let logger: Logger

    public init(_ inner: any GenerativeQuestionServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-retail-v2"
      logger[metadataKey: "gcp.client.service"] = "retail"
      logger[metadataKey: "gcp.experimental.swift.client"] = "GenerativeQuestionService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func updateGenerativeQuestionsFeatureConfig(
      request: UpdateGenerativeQuestionsFeatureConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.GenerativeQuestionsFeatureConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateGenerativeQuestionsFeatureConfig",
        action: {
          (r: UpdateGenerativeQuestionsFeatureConfigRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudRetailV2.GenerativeQuestionsFeatureConfig
          in
          return try await self.inner.updateGenerativeQuestionsFeatureConfig(request: r, options: o)
        })
    }

    public func getGenerativeQuestionsFeatureConfig(
      request: GetGenerativeQuestionsFeatureConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.GenerativeQuestionsFeatureConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getGenerativeQuestionsFeatureConfig",
        action: {
          (r: GetGenerativeQuestionsFeatureConfigRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudRetailV2.GenerativeQuestionsFeatureConfig
          in
          return try await self.inner.getGenerativeQuestionsFeatureConfig(request: r, options: o)
        })
    }

    public func listGenerativeQuestionConfigs(
      request: ListGenerativeQuestionConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.ListGenerativeQuestionConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listGenerativeQuestionConfigs",
        action: {
          (r: ListGenerativeQuestionConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.ListGenerativeQuestionConfigsResponse
          in
          return try await self.inner.listGenerativeQuestionConfigs(request: r, options: o)
        })
    }

    public func updateGenerativeQuestionConfig(
      request: UpdateGenerativeQuestionConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.GenerativeQuestionConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateGenerativeQuestionConfig",
        action: {
          (r: UpdateGenerativeQuestionConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.GenerativeQuestionConfig
          in
          return try await self.inner.updateGenerativeQuestionConfig(request: r, options: o)
        })
    }

    public func batchUpdateGenerativeQuestionConfigs(
      request: BatchUpdateGenerativeQuestionConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.BatchUpdateGenerativeQuestionConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchUpdateGenerativeQuestionConfigs",
        action: {
          (r: BatchUpdateGenerativeQuestionConfigsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudRetailV2.BatchUpdateGenerativeQuestionConfigsResponse
          in
          return try await self.inner.batchUpdateGenerativeQuestionConfigs(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
