// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Metadata related to the progress of the Import operation. This is
/// returned by the google.longrunning.Operation.metadata field.
public struct ImportMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Operation create time.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Operation last update time. If the operation is done, this is also the
  /// finish time.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Count of entries that were processed successfully.
  public var successCount: Swift.Int64 = Swift.Int64()

  /// Count of entries that encountered errors while processing.
  public var failureCount: Swift.Int64 = Swift.Int64()

  /// Deprecated. This field is never set.
  @available(*, deprecated)
  public var requestId: Swift.String = Swift.String()

  /// Pub/Sub topic for receiving notification. If this field is set,
  /// when the import is finished, a notification is sent to
  /// specified Pub/Sub topic. The message data is JSON string of a
  /// [Operation][google.longrunning.Operation].
  /// Format of the Pub/Sub topic is `projects/{project}/topics/{topic}`.
  ///
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  public var notificationPubsubTopic: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImportMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportMetadata().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let successCount = CodingKeys(stringValue: "successCount")
    static let failureCount = CodingKeys(stringValue: "failureCount")
    static let requestId = CodingKeys(stringValue: "requestId")
    static let notificationPubsubTopic = CodingKeys(stringValue: "notificationPubsubTopic")

    static let _knownKeys: Set<Swift.String> = [
      "createTime",
      "updateTime",
      "successCount",
      "failureCount",
      "requestId",
      "notificationPubsubTopic",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .successCount) {
      self.successCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .failureCount) {
      self.failureCount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .notificationPubsubTopic)
    {
      self.notificationPubsubTopic = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.successCount, forKey: .successCount)
    try container.encode(self.failureCount, forKey: .failureCount)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encode(self.notificationPubsubTopic, forKey: .notificationPubsubTopic)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.ImportMetadata"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
