// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request for
/// [CatalogService.ListCatalogs][google.cloud.retail.v2.CatalogService.ListCatalogs]
/// method.
///
/// [google.cloud.retail.v2.CatalogService.ListCatalogs]: <doc:CatalogServiceClient/listCatalogs(request:options:)>
public struct ListCatalogsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The account resource name with an associated location.
  ///
  /// If the caller does not have permission to list
  /// [Catalog][google.cloud.retail.v2.Catalog]s under this location, regardless
  /// of whether or not this location exists, a PERMISSION_DENIED error is
  /// returned.
  ///
  /// [google.cloud.retail.v2.Catalog]: <doc:Catalog>
  public var parent: Swift.String = Swift.String()

  /// Maximum number of [Catalog][google.cloud.retail.v2.Catalog]s to return. If
  /// unspecified, defaults to 50. The maximum allowed value is 1000. Values
  /// above 1000 will be coerced to 1000.
  ///
  /// If this field is negative, an INVALID_ARGUMENT is returned.
  ///
  /// [google.cloud.retail.v2.Catalog]: <doc:Catalog>
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token
  /// [ListCatalogsResponse.next_page_token][google.cloud.retail.v2.ListCatalogsResponse.next_page_token],
  /// received from a previous
  /// [CatalogService.ListCatalogs][google.cloud.retail.v2.CatalogService.ListCatalogs]
  /// call. Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// [CatalogService.ListCatalogs][google.cloud.retail.v2.CatalogService.ListCatalogs]
  /// must match the call that provided the page token. Otherwise, an
  /// INVALID_ARGUMENT error is returned.
  ///
  /// [google.cloud.retail.v2.CatalogService.ListCatalogs]: <doc:CatalogServiceClient/listCatalogs(request:options:)>
  /// [google.cloud.retail.v2.ListCatalogsResponse.next_page_token]: <doc:ListCatalogsResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListCatalogsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCatalogsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.ListCatalogsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
