// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ModelServiceLogging: ModelServiceStub {
    let inner: any ModelServiceStub
    let logger: Logger

    public init(_ inner: any ModelServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-retail-v2"
      logger[metadataKey: "gcp.client.service"] = "retail"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ModelService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createModel(
      request: CreateModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createModel",
        action: {
          (r: CreateModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createModel(request: r, options: o)
        })
    }

    public func getModel(
      request: GetModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.Model {
      try await self._intercept(
        request: request,
        options: options,
        name: "getModel",
        action: {
          (r: GetModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.Model
          in
          return try await self.inner.getModel(request: r, options: o)
        })
    }

    public func pauseModel(
      request: PauseModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.Model {
      try await self._intercept(
        request: request,
        options: options,
        name: "pauseModel",
        action: {
          (r: PauseModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.Model
          in
          return try await self.inner.pauseModel(request: r, options: o)
        })
    }

    public func resumeModel(
      request: ResumeModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.Model {
      try await self._intercept(
        request: request,
        options: options,
        name: "resumeModel",
        action: {
          (r: ResumeModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.Model
          in
          return try await self.inner.resumeModel(request: r, options: o)
        })
    }

    public func deleteModel(
      request: DeleteModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteModel",
        action: { (r: DeleteModelRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteModel(request: r, options: o)
        })
    }

    public func listModels(
      request: ListModelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.ListModelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listModels",
        action: {
          (r: ListModelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.ListModelsResponse
          in
          return try await self.inner.listModels(request: r, options: o)
        })
    }

    public func updateModel(
      request: UpdateModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.Model {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateModel",
        action: {
          (r: UpdateModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.Model
          in
          return try await self.inner.updateModel(request: r, options: o)
        })
    }

    public func tuneModel(
      request: TuneModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "tuneModel",
        action: {
          (r: TuneModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.tuneModel(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
