// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  final class ModelServiceRetry: ModelServiceStub {
    let inner: any ModelServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any ModelServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createModel(
      request: CreateModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.createModel(request: r, options: o)
        })
    }

    public func getModel(
      request: GetModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.Model {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.Model
          in
          return try await self.inner.getModel(request: r, options: o)
        })
    }

    public func pauseModel(
      request: PauseModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.Model {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: PauseModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.Model
          in
          return try await self.inner.pauseModel(request: r, options: o)
        })
    }

    public func resumeModel(
      request: ResumeModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.Model {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ResumeModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.Model
          in
          return try await self.inner.resumeModel(request: r, options: o)
        })
    }

    public func deleteModel(
      request: DeleteModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteModelRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteModel(request: r, options: o)
        })
    }

    public func listModels(
      request: ListModelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.ListModelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListModelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.ListModelsResponse
          in
          return try await self.inner.listModels(request: r, options: o)
        })
    }

    public func updateModel(
      request: UpdateModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRetailV2.Model {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRetailV2.Model
          in
          return try await self.inner.updateModel(request: r, options: o)
        })
    }

    public func tuneModel(
      request: TuneModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: TuneModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.tuneModel(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
