// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Metadata that describes the training and serving parameters of a
/// [Model][google.cloud.retail.v2.Model]. A
/// [Model][google.cloud.retail.v2.Model] can be associated with a
/// [ServingConfig][google.cloud.retail.v2.ServingConfig] and then queried
/// through the Predict API.
///
/// [google.cloud.retail.v2.Model]: <doc:Model>
/// [google.cloud.retail.v2.ServingConfig]: <doc:ServingConfig>
public struct Model: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The fully qualified resource name of the model.
  ///
  /// Format:
  /// `projects/{project_number}/locations/{location_id}/catalogs/{catalog_id}/models/{model_id}`
  /// catalog_id has char limit of 50.
  /// recommendation_model_id has char limit of 40.
  public var name: Swift.String = Swift.String()

  /// Required. The display name of the model.
  ///
  /// Should be human readable, used to display Recommendation Models in the
  /// Retail Cloud Console Dashboard. UTF-8 encoded string with limit of 1024
  /// characters.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The training state that the model is in (e.g.
  /// `TRAINING` or `PAUSED`).
  ///
  /// Since part of the cost of running the service
  /// is frequency of training - this can be used to determine when to train
  /// model in order to control cost. If not specified: the default value for
  /// `CreateModel` method is `TRAINING`. The default value for
  /// `UpdateModel` method is to keep the state the same as before.
  public var trainingState: Model.TrainingState = Model.TrainingState()

  /// Output only. The serving state of the model: `ACTIVE`, `NOT_ACTIVE`.
  public var servingState: Model.ServingState = Model.ServingState()

  /// Output only. Timestamp the Recommendation Model was created at.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Timestamp the Recommendation Model was last updated. E.g.
  /// if a Recommendation Model was paused - this would be the time the pause was
  /// initiated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Required. The type of model e.g. `home-page`.
  ///
  /// Currently supported values: `recommended-for-you`, `others-you-may-like`,
  /// `frequently-bought-together`, `page-optimization`, `similar-items`,
  /// `buy-it-again`, `on-sale-items`, and `recently-viewed`(readonly value).
  ///
  /// This field together with
  /// [optimization_objective][google.cloud.retail.v2.Model.optimization_objective]
  /// describe model metadata to use to control model training and serving.
  /// See https://cloud.google.com/retail/docs/models
  /// for more details on what the model metadata control and which combination
  /// of parameters are valid. For invalid combinations of parameters (e.g. type
  /// = `frequently-bought-together` and optimization_objective = `ctr`), you
  /// receive an error 400 if you try to create/update a recommendation with
  /// this set of knobs.
  ///
  /// [google.cloud.retail.v2.Model.optimization_objective]: <doc:Model/optimizationObjective>
  public var type: Swift.String = Swift.String()

  /// Optional. The optimization objective e.g. `cvr`.
  ///
  /// Currently supported
  /// values: `ctr`, `cvr`, `revenue-per-order`.
  ///
  ///  If not specified, we choose default based on model type.
  /// Default depends on type of recommendation:
  ///
  /// `recommended-for-you` => `ctr`
  ///
  /// `others-you-may-like` => `ctr`
  ///
  /// `frequently-bought-together` => `revenue_per_order`
  ///
  /// This field together with
  /// [optimization_objective][google.cloud.retail.v2.Model.type]
  /// describe model metadata to use to control model training and serving.
  /// See https://cloud.google.com/retail/docs/models
  /// for more details on what the model metadata control and which combination
  /// of parameters are valid. For invalid combinations of parameters (e.g. type
  /// = `frequently-bought-together` and optimization_objective = `ctr`), you
  /// receive an error 400 if you try to create/update a recommendation with
  /// this set of knobs.
  ///
  /// [google.cloud.retail.v2.Model.type]: <doc:Model/type>
  public var optimizationObjective: Swift.String = Swift.String()

  /// Optional. The state of periodic tuning.
  ///
  /// The period we use is 3 months - to do a
  /// one-off tune earlier use the `TuneModel` method. Default value
  /// is `PERIODIC_TUNING_ENABLED`.
  public var periodicTuningState: Model.PeriodicTuningState = Model.PeriodicTuningState()

  /// Output only. The timestamp when the latest successful tune finished.
  public var lastTuneTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The tune operation associated with the model.
  ///
  /// Can be used to determine if there is an ongoing tune for this
  /// recommendation. Empty field implies no tune is goig on.
  public var tuningOperation: Swift.String = Swift.String()

  /// Output only. The state of data requirements for this model: `DATA_OK` and
  /// `DATA_ERROR`.
  ///
  /// Recommendation model cannot be trained if the data is in
  /// `DATA_ERROR` state. Recommendation model can have `DATA_ERROR` state even
  /// if serving state is `ACTIVE`: models were trained successfully before, but
  /// cannot be refreshed because model no longer has sufficient
  /// data for training.
  public var dataState: Model.DataState = Model.DataState()

  /// Optional. If `RECOMMENDATIONS_FILTERING_ENABLED`, recommendation filtering
  /// by attributes is enabled for the model.
  public var filteringOption: RecommendationsFilteringOption = RecommendationsFilteringOption()

  /// Output only. The list of valid serving configs associated with the
  /// PageOptimizationConfig.
  public var servingConfigLists: [Model.ServingConfigList] = []

  /// Optional. Additional model features config.
  public var modelFeaturesConfig: Model.ModelFeaturesConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Model`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Model().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let trainingState = CodingKeys(stringValue: "trainingState")
    static let servingState = CodingKeys(stringValue: "servingState")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let type = CodingKeys(stringValue: "type")
    static let optimizationObjective = CodingKeys(stringValue: "optimizationObjective")
    static let periodicTuningState = CodingKeys(stringValue: "periodicTuningState")
    static let lastTuneTime = CodingKeys(stringValue: "lastTuneTime")
    static let tuningOperation = CodingKeys(stringValue: "tuningOperation")
    static let dataState = CodingKeys(stringValue: "dataState")
    static let filteringOption = CodingKeys(stringValue: "filteringOption")
    static let servingConfigLists = CodingKeys(stringValue: "servingConfigLists")
    static let modelFeaturesConfig = CodingKeys(stringValue: "modelFeaturesConfig")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "trainingState",
      "servingState",
      "createTime",
      "updateTime",
      "type",
      "optimizationObjective",
      "periodicTuningState",
      "lastTuneTime",
      "tuningOperation",
      "dataState",
      "filteringOption",
      "servingConfigLists",
      "modelFeaturesConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Model.TrainingState.self, forKey: .trainingState) {
      self.trainingState = value
    }
    if let value = try container.decodeIfPresent(Model.ServingState.self, forKey: .servingState) {
      self.servingState = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .optimizationObjective)
    {
      self.optimizationObjective = value
    }
    if let value = try container.decodeIfPresent(
      Model.PeriodicTuningState.self, forKey: .periodicTuningState)
    {
      self.periodicTuningState = value
    }
    self.lastTuneTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastTuneTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tuningOperation) {
      self.tuningOperation = value
    }
    if let value = try container.decodeIfPresent(Model.DataState.self, forKey: .dataState) {
      self.dataState = value
    }
    if let value = try container.decodeIfPresent(
      RecommendationsFilteringOption.self, forKey: .filteringOption)
    {
      self.filteringOption = value
    }
    if let value = try container.decodeIfPresent(
      [Model.ServingConfigList].self, forKey: .servingConfigLists)
    {
      self.servingConfigLists = value
    }
    self.modelFeaturesConfig = try container.decodeIfPresent(
      Model.ModelFeaturesConfig.self, forKey: .modelFeaturesConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.trainingState, forKey: .trainingState)
    try container.encode(self.servingState, forKey: .servingState)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.optimizationObjective, forKey: .optimizationObjective)
    try container.encode(self.periodicTuningState, forKey: .periodicTuningState)
    try container.encodeIfPresent(self.lastTuneTime, forKey: .lastTuneTime)
    try container.encode(self.tuningOperation, forKey: .tuningOperation)
    try container.encode(self.dataState, forKey: .dataState)
    try container.encode(self.filteringOption, forKey: .filteringOption)
    try container.encode(self.servingConfigLists, forKey: .servingConfigLists)
    try container.encodeIfPresent(self.modelFeaturesConfig, forKey: .modelFeaturesConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents an ordered combination of valid serving configs, which
  /// can be used for `PAGE_OPTIMIZATION` recommendations.
  public struct ServingConfigList: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. A set of valid serving configs that may be used for
    /// `PAGE_OPTIMIZATION`.
    public var servingConfigIds: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ServingConfigList`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ServingConfigList().with { $0.servingConfigIds = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let servingConfigIds = CodingKeys(stringValue: "servingConfigIds")

      static let _knownKeys: Set<Swift.String> = [
        "servingConfigIds"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .servingConfigIds) {
        self.servingConfigIds = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.servingConfigIds, forKey: .servingConfigIds)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Model.ServingConfigList"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Additional configs for the frequently-bought-together model type.
  public struct FrequentlyBoughtTogetherFeaturesConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Specifies the context of the model when it is used in predict
    /// requests. Can only be set for the `frequently-bought-together` type. If
    /// it isn't specified, it defaults to
    /// [MULTIPLE_CONTEXT_PRODUCTS][google.cloud.retail.v2.Model.ContextProductsType.MULTIPLE_CONTEXT_PRODUCTS].
    ///
    /// [google.cloud.retail.v2.Model.ContextProductsType.MULTIPLE_CONTEXT_PRODUCTS]: <doc:Model/ContextProductsType/multipleContextProducts>
    public var contextProductsType: Model.ContextProductsType = Model.ContextProductsType()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FrequentlyBoughtTogetherFeaturesConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FrequentlyBoughtTogetherFeaturesConfig().with { $0.contextProductsType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let contextProductsType = CodingKeys(stringValue: "contextProductsType")

      static let _knownKeys: Set<Swift.String> = [
        "contextProductsType"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Model.ContextProductsType.self, forKey: .contextProductsType)
      {
        self.contextProductsType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.contextProductsType, forKey: .contextProductsType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.retail.v2.Model.FrequentlyBoughtTogetherFeaturesConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Additional model features config.
  public struct ModelFeaturesConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var typeDedicatedConfig: TypeDedicatedConfigOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ModelFeaturesConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ModelFeaturesConfig().with { $0.frequentlyBoughtTogetherConfig = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let frequentlyBoughtTogetherConfig = CodingKeys(
        stringValue: "frequentlyBoughtTogetherConfig")

      static let _knownKeys: Set<Swift.String> = [
        "frequentlyBoughtTogetherConfig"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var typeDedicatedConfig: TypeDedicatedConfigOneOf? = nil
      let typeDedicatedConfigCheckAndSet = {
        if typeDedicatedConfig != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'typeDedicatedConfig'"))
        }
        typeDedicatedConfig = $0
      }
      if let frequentlyBoughtTogetherConfig = try container.decodeIfPresent(
        Model.FrequentlyBoughtTogetherFeaturesConfig?.self, forKey: .frequentlyBoughtTogetherConfig)
      {
        try typeDedicatedConfigCheckAndSet(
          .frequentlyBoughtTogetherConfig(frequentlyBoughtTogetherConfig))
      }
      self.typeDedicatedConfig = typeDedicatedConfig
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.typeDedicatedConfig {
        switch choice {
        case .frequentlyBoughtTogetherConfig(let value):
          try container.encode(value, forKey: .frequentlyBoughtTogetherConfig)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public enum TypeDedicatedConfigOneOf: Codable, Equatable, Sendable {
      /// Additional configs for frequently-bought-together models.
      indirect case frequentlyBoughtTogetherConfig(Model.FrequentlyBoughtTogetherFeaturesConfig?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Model.ModelFeaturesConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The serving state of the model.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ServingState: Codable, Equatable, Hashable, Sendable {
    /// Unspecified serving state.
    case unspecified
    /// The model is not serving.
    case inactive
    /// The model is serving and can be queried.
    case active
    /// The model is trained on tuned hyperparameters and can be
    /// queried.
    case tuned
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inactive: return 1
      case .active: return 2
      case .tuned: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SERVING_STATE_UNSPECIFIED"
      case .inactive: return "INACTIVE"
      case .active: return "ACTIVE"
      case .tuned: return "TUNED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ServingState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SERVING_STATE_UNSPECIFIED": self = .unspecified
      case "INACTIVE": self = .inactive
      case "ACTIVE": self = .active
      case "TUNED": self = .tuned
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ServingState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inactive
      case 2: self = .active
      case 3: self = .tuned
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SERVING_STATE_UNSPECIFIED")
      case .inactive: return try container.encode("INACTIVE")
      case .active: return try container.encode("ACTIVE")
      case .tuned: return try container.encode("TUNED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The training state of the model.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum TrainingState: Codable, Equatable, Hashable, Sendable {
    /// Unspecified training state.
    case unspecified
    /// The model training is paused.
    case paused
    /// The model is training.
    case training
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .paused: return 1
      case .training: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TRAINING_STATE_UNSPECIFIED"
      case .paused: return "PAUSED"
      case .training: return "TRAINING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TrainingState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TRAINING_STATE_UNSPECIFIED": self = .unspecified
      case "PAUSED": self = .paused
      case "TRAINING": self = .training
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TrainingState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .paused
      case 2: self = .training
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TRAINING_STATE_UNSPECIFIED")
      case .paused: return try container.encode("PAUSED")
      case .training: return try container.encode("TRAINING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Describes whether periodic tuning is enabled for this model
  /// or not. Periodic tuning is scheduled at most every three months. You can
  /// start a tuning process manually by using the `TuneModel`
  /// method, which starts a tuning process immediately and resets the quarterly
  /// schedule. Enabling or disabling periodic tuning does not affect any
  /// current tuning processes.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum PeriodicTuningState: Codable, Equatable, Hashable, Sendable {
    /// Unspecified default value, should never be explicitly set.
    case unspecified
    /// The model has periodic tuning disabled. Tuning
    /// can be reenabled by calling the `EnableModelPeriodicTuning`
    /// method or by calling the `TuneModel` method.
    case periodicTuningDisabled
    /// The model has periodic tuning enabled. Tuning
    /// can be disabled by calling the `DisableModelPeriodicTuning`
    /// method.
    case periodicTuningEnabled
    /// The model cannot be tuned with periodic tuning OR the
    /// `TuneModel` method. Hide the options in customer UI and
    /// reject any requests through the backend self serve API.
    case allTuningDisabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .periodicTuningDisabled: return 1
      case .periodicTuningEnabled: return 2
      case .allTuningDisabled: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PERIODIC_TUNING_STATE_UNSPECIFIED"
      case .periodicTuningDisabled: return "PERIODIC_TUNING_DISABLED"
      case .periodicTuningEnabled: return "PERIODIC_TUNING_ENABLED"
      case .allTuningDisabled: return "ALL_TUNING_DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PeriodicTuningState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PERIODIC_TUNING_STATE_UNSPECIFIED": self = .unspecified
      case "PERIODIC_TUNING_DISABLED": self = .periodicTuningDisabled
      case "ALL_TUNING_DISABLED": self = .allTuningDisabled
      case "PERIODIC_TUNING_ENABLED": self = .periodicTuningEnabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PeriodicTuningState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .periodicTuningDisabled
      case 2: self = .periodicTuningEnabled
      case 3: self = .allTuningDisabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PERIODIC_TUNING_STATE_UNSPECIFIED")
      case .periodicTuningDisabled: return try container.encode("PERIODIC_TUNING_DISABLED")
      case .periodicTuningEnabled: return try container.encode("PERIODIC_TUNING_ENABLED")
      case .allTuningDisabled: return try container.encode("ALL_TUNING_DISABLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Describes whether this model have sufficient training data
  /// to be continuously trained.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DataState: Codable, Equatable, Hashable, Sendable {
    /// Unspecified default value, should never be explicitly set.
    case unspecified
    /// The model has sufficient training data.
    case dataOk
    /// The model does not have sufficient training data. Error
    /// messages can be queried via Stackdriver.
    case dataError
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .dataOk: return 1
      case .dataError: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DATA_STATE_UNSPECIFIED"
      case .dataOk: return "DATA_OK"
      case .dataError: return "DATA_ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DataState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DATA_STATE_UNSPECIFIED": self = .unspecified
      case "DATA_OK": self = .dataOk
      case "DATA_ERROR": self = .dataError
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DataState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .dataOk
      case 2: self = .dataError
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DATA_STATE_UNSPECIFIED")
      case .dataOk: return try container.encode("DATA_OK")
      case .dataError: return try container.encode("DATA_ERROR")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Use single or multiple context products for recommendations.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ContextProductsType: Codable, Equatable, Hashable, Sendable {
    /// Unspecified default value, should never be explicitly set.
    /// Defaults to
    /// [MULTIPLE_CONTEXT_PRODUCTS][google.cloud.retail.v2.Model.ContextProductsType.MULTIPLE_CONTEXT_PRODUCTS].
    ///
    /// [google.cloud.retail.v2.Model.ContextProductsType.MULTIPLE_CONTEXT_PRODUCTS]: <doc:Model/ContextProductsType/multipleContextProducts>
    case unspecified
    /// Use only a single product as context for the recommendation. Typically
    /// used on pages like add-to-cart or product details.
    case singleContextProduct
    /// Use one or multiple products as context for the recommendation. Typically
    /// used on shopping cart pages.
    case multipleContextProducts
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .singleContextProduct: return 1
      case .multipleContextProducts: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONTEXT_PRODUCTS_TYPE_UNSPECIFIED"
      case .singleContextProduct: return "SINGLE_CONTEXT_PRODUCT"
      case .multipleContextProducts: return "MULTIPLE_CONTEXT_PRODUCTS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ContextProductsType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONTEXT_PRODUCTS_TYPE_UNSPECIFIED": self = .unspecified
      case "SINGLE_CONTEXT_PRODUCT": self = .singleContextProduct
      case "MULTIPLE_CONTEXT_PRODUCTS": self = .multipleContextProducts
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ContextProductsType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .singleContextProduct
      case 2: self = .multipleContextProducts
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CONTEXT_PRODUCTS_TYPE_UNSPECIFIED")
      case .singleContextProduct: return try container.encode("SINGLE_CONTEXT_PRODUCT")
      case .multipleContextProducts: return try container.encode("MULTIPLE_CONTEXT_PRODUCTS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.Model"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
