// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The price information of a [Product][google.cloud.retail.v2.Product].
///
/// [google.cloud.retail.v2.Product]: <doc:Product>
public struct PriceInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The 3-letter currency code defined in [ISO
  /// 4217](https://www.iso.org/iso-4217-currency-codes.html).
  ///
  /// If this field is an unrecognizable currency code, an INVALID_ARGUMENT
  /// error is returned.
  ///
  /// The [Product.Type.VARIANT][google.cloud.retail.v2.Product.Type.VARIANT]
  /// [Product][google.cloud.retail.v2.Product]s with the same
  /// [Product.primary_product_id][google.cloud.retail.v2.Product.primary_product_id]
  /// must share the same
  /// [currency_code][google.cloud.retail.v2.PriceInfo.currency_code]. Otherwise,
  /// a FAILED_PRECONDITION error is returned.
  ///
  /// [google.cloud.retail.v2.PriceInfo.currency_code]: <doc:PriceInfo/currencyCode>
  /// [google.cloud.retail.v2.Product]: <doc:Product>
  /// [google.cloud.retail.v2.Product.Type.VARIANT]: <doc:Product/Type_/variant>
  /// [google.cloud.retail.v2.Product.primary_product_id]: <doc:Product/primaryProductId>
  public var currencyCode: Swift.String = Swift.String()

  /// Price of the product.
  ///
  /// Google Merchant Center property
  /// [price](https://support.google.com/merchants/answer/6324371). Schema.org
  /// property [Offer.price](https://schema.org/price).
  public var price: Swift.Float = Swift.Float()

  /// Price of the product without any discount. If zero, by default set to be
  /// the [price][google.cloud.retail.v2.PriceInfo.price]. If set,
  /// [original_price][google.cloud.retail.v2.PriceInfo.original_price] should be
  /// greater than or equal to [price][google.cloud.retail.v2.PriceInfo.price],
  /// otherwise an INVALID_ARGUMENT error is thrown.
  ///
  /// [google.cloud.retail.v2.PriceInfo.original_price]: <doc:PriceInfo/originalPrice>
  /// [google.cloud.retail.v2.PriceInfo.price]: <doc:PriceInfo/price>
  public var originalPrice: Swift.Float = Swift.Float()

  /// The costs associated with the sale of a particular product. Used for gross
  /// profit reporting.
  ///
  /// * Profit = [price][google.cloud.retail.v2.PriceInfo.price] -
  /// [cost][google.cloud.retail.v2.PriceInfo.cost]
  ///
  /// Google Merchant Center property
  /// [cost_of_goods_sold](https://support.google.com/merchants/answer/9017895).
  ///
  /// [google.cloud.retail.v2.PriceInfo.cost]: <doc:PriceInfo/cost>
  /// [google.cloud.retail.v2.PriceInfo.price]: <doc:PriceInfo/price>
  public var cost: Swift.Float = Swift.Float()

  /// The timestamp when the [price][google.cloud.retail.v2.PriceInfo.price]
  /// starts to be effective. This can be set as a future timestamp, and the
  /// [price][google.cloud.retail.v2.PriceInfo.price] is only used for search
  /// after
  /// [price_effective_time][google.cloud.retail.v2.PriceInfo.price_effective_time].
  /// If so, the
  /// [original_price][google.cloud.retail.v2.PriceInfo.original_price] must be
  /// set and [original_price][google.cloud.retail.v2.PriceInfo.original_price]
  /// is used before
  /// [price_effective_time][google.cloud.retail.v2.PriceInfo.price_effective_time].
  ///
  /// Do not set if [price][google.cloud.retail.v2.PriceInfo.price] is always
  /// effective because it will cause additional latency during search.
  ///
  /// [google.cloud.retail.v2.PriceInfo.original_price]: <doc:PriceInfo/originalPrice>
  /// [google.cloud.retail.v2.PriceInfo.price]: <doc:PriceInfo/price>
  /// [google.cloud.retail.v2.PriceInfo.price_effective_time]: <doc:PriceInfo/priceEffectiveTime>
  public var priceEffectiveTime: GoogleWKT.Timestamp? = nil

  /// The timestamp when the [price][google.cloud.retail.v2.PriceInfo.price]
  /// stops to be effective. The [price][google.cloud.retail.v2.PriceInfo.price]
  /// is used for search before
  /// [price_expire_time][google.cloud.retail.v2.PriceInfo.price_expire_time]. If
  /// this field is set, the
  /// [original_price][google.cloud.retail.v2.PriceInfo.original_price] must be
  /// set and [original_price][google.cloud.retail.v2.PriceInfo.original_price]
  /// is used after
  /// [price_expire_time][google.cloud.retail.v2.PriceInfo.price_expire_time].
  ///
  /// Do not set if [price][google.cloud.retail.v2.PriceInfo.price] is always
  /// effective because it will cause additional latency during search.
  ///
  /// [google.cloud.retail.v2.PriceInfo.original_price]: <doc:PriceInfo/originalPrice>
  /// [google.cloud.retail.v2.PriceInfo.price]: <doc:PriceInfo/price>
  /// [google.cloud.retail.v2.PriceInfo.price_expire_time]: <doc:PriceInfo/priceExpireTime>
  public var priceExpireTime: GoogleWKT.Timestamp? = nil

  /// Output only. The price range of all the child
  /// [Product.Type.VARIANT][google.cloud.retail.v2.Product.Type.VARIANT]
  /// [Product][google.cloud.retail.v2.Product]s grouped together on the
  /// [Product.Type.PRIMARY][google.cloud.retail.v2.Product.Type.PRIMARY]
  /// [Product][google.cloud.retail.v2.Product]. Only populated for
  /// [Product.Type.PRIMARY][google.cloud.retail.v2.Product.Type.PRIMARY]
  /// [Product][google.cloud.retail.v2.Product]s.
  ///
  /// Note: This field is OUTPUT_ONLY for
  /// [ProductService.GetProduct][google.cloud.retail.v2.ProductService.GetProduct].
  /// Do not set this field in API requests.
  ///
  /// [google.cloud.retail.v2.Product]: <doc:Product>
  /// [google.cloud.retail.v2.Product.Type.PRIMARY]: <doc:Product/Type_/primary>
  /// [google.cloud.retail.v2.Product.Type.VARIANT]: <doc:Product/Type_/variant>
  /// [google.cloud.retail.v2.ProductService.GetProduct]: <doc:ProductServiceClient/getProduct(request:options:)>
  public var priceRange: PriceInfo.PriceRange? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PriceInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PriceInfo().with { $0.currencyCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let currencyCode = CodingKeys(stringValue: "currencyCode")
    static let price = CodingKeys(stringValue: "price")
    static let originalPrice = CodingKeys(stringValue: "originalPrice")
    static let cost = CodingKeys(stringValue: "cost")
    static let priceEffectiveTime = CodingKeys(stringValue: "priceEffectiveTime")
    static let priceExpireTime = CodingKeys(stringValue: "priceExpireTime")
    static let priceRange = CodingKeys(stringValue: "priceRange")

    static let _knownKeys: Set<Swift.String> = [
      "currencyCode",
      "price",
      "originalPrice",
      "cost",
      "priceEffectiveTime",
      "priceExpireTime",
      "priceRange",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .currencyCode) {
      self.currencyCode = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .price) {
      self.price = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .originalPrice) {
      self.originalPrice = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .cost) {
      self.cost = value
    }
    self.priceEffectiveTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .priceEffectiveTime)
    self.priceExpireTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .priceExpireTime)
    self.priceRange = try container.decodeIfPresent(PriceInfo.PriceRange.self, forKey: .priceRange)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.currencyCode, forKey: .currencyCode)
    try container.encode(self.price, forKey: .price)
    try container.encode(self.originalPrice, forKey: .originalPrice)
    try container.encode(self.cost, forKey: .cost)
    try container.encodeIfPresent(self.priceEffectiveTime, forKey: .priceEffectiveTime)
    try container.encodeIfPresent(self.priceExpireTime, forKey: .priceExpireTime)
    try container.encodeIfPresent(self.priceRange, forKey: .priceRange)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The price range of all
  /// [variant][google.cloud.retail.v2.Product.Type.VARIANT]
  /// [Product][google.cloud.retail.v2.Product] having the same
  /// [Product.primary_product_id][google.cloud.retail.v2.Product.primary_product_id].
  ///
  /// [google.cloud.retail.v2.Product]: <doc:Product>
  /// [google.cloud.retail.v2.Product.Type.VARIANT]: <doc:Product/Type_/variant>
  /// [google.cloud.retail.v2.Product.primary_product_id]: <doc:Product/primaryProductId>
  public struct PriceRange: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The inclusive
    /// [Product.pricing_info.price][google.cloud.retail.v2.PriceInfo.price]
    /// interval of all [variant][google.cloud.retail.v2.Product.Type.VARIANT]
    /// [Product][google.cloud.retail.v2.Product] having the same
    /// [Product.primary_product_id][google.cloud.retail.v2.Product.primary_product_id].
    ///
    /// [google.cloud.retail.v2.PriceInfo.price]: <doc:PriceInfo/price>
    /// [google.cloud.retail.v2.Product]: <doc:Product>
    /// [google.cloud.retail.v2.Product.Type.VARIANT]: <doc:Product/Type_/variant>
    /// [google.cloud.retail.v2.Product.primary_product_id]: <doc:Product/primaryProductId>
    public var price: Interval? = nil

    /// The inclusive
    /// [Product.pricing_info.original_price][google.cloud.retail.v2.PriceInfo.original_price]
    /// internal of all [variant][google.cloud.retail.v2.Product.Type.VARIANT]
    /// [Product][google.cloud.retail.v2.Product] having the same
    /// [Product.primary_product_id][google.cloud.retail.v2.Product.primary_product_id].
    ///
    /// [google.cloud.retail.v2.PriceInfo.original_price]: <doc:PriceInfo/originalPrice>
    /// [google.cloud.retail.v2.Product]: <doc:Product>
    /// [google.cloud.retail.v2.Product.Type.VARIANT]: <doc:Product/Type_/variant>
    /// [google.cloud.retail.v2.Product.primary_product_id]: <doc:Product/primaryProductId>
    public var originalPrice: Interval? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PriceRange`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PriceRange().with { $0.price = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let price = CodingKeys(stringValue: "price")
      static let originalPrice = CodingKeys(stringValue: "originalPrice")

      static let _knownKeys: Set<Swift.String> = [
        "price",
        "originalPrice",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.price = try container.decodeIfPresent(Interval.self, forKey: .price)
      self.originalPrice = try container.decodeIfPresent(Interval.self, forKey: .originalPrice)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.price, forKey: .price)
      try container.encodeIfPresent(self.originalPrice, forKey: .originalPrice)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.PriceInfo.PriceRange"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.PriceInfo"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
