// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for PurgeProducts method.
public struct PurgeProductsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the branch under which the products are
  /// created. The format is
  /// `projects/${projectId}/locations/global/catalogs/${catalogId}/branches/${branchId}`
  public var parent: Swift.String = Swift.String()

  /// Required. The filter string to specify the products to be deleted with a
  /// length limit of 5,000 characters.
  ///
  /// Empty string filter is not allowed. "*" implies delete all items in a
  /// branch.
  ///
  /// The eligible fields for filtering are:
  ///
  /// * `availability`: Double quoted
  /// [Product.availability][google.cloud.retail.v2.Product.availability] string.
  /// * `create_time` : in ISO 8601 "zulu" format.
  ///
  /// Supported syntax:
  ///
  /// * Comparators (">", "<", ">=", "<=", "=").
  ///   Examples:
  ///   * create_time <= "2015-02-13T17:05:46Z"
  ///   * availability = "IN_STOCK"
  ///
  /// * Conjunctions ("AND")
  ///   Examples:
  ///   * create_time <= "2015-02-13T17:05:46Z" AND availability = "PREORDER"
  ///
  /// * Disjunctions ("OR")
  ///   Examples:
  ///   * create_time <= "2015-02-13T17:05:46Z" OR availability = "IN_STOCK"
  ///
  /// * Can support nested queries.
  ///   Examples:
  ///   * (create_time <= "2015-02-13T17:05:46Z" AND availability = "PREORDER")
  ///   OR (create_time >= "2015-02-14T13:03:32Z" AND availability = "IN_STOCK")
  ///
  /// * Filter Limits:
  ///   * Filter should not contain more than 6 conditions.
  ///   * Max nesting depth should not exceed 2 levels.
  ///
  /// Examples queries:
  /// * Delete back order products created before a timestamp.
  ///   create_time <= "2015-02-13T17:05:46Z" OR availability = "BACKORDER"
  ///
  /// [google.cloud.retail.v2.Product.availability]: <doc:Product/availability>
  public var filter: Swift.String = Swift.String()

  /// Actually perform the purge.
  /// If `force` is set to false, the method will return the expected purge count
  /// without deleting any products.
  public var force: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `PurgeProductsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PurgeProductsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.PurgeProductsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
