// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A rule is a condition-action pair
///
/// * A condition defines when a rule is to be triggered.
/// * An action specifies what occurs on that trigger.
/// Currently rules only work for [controls][google.cloud.retail.v2.Control] with
/// [SOLUTION_TYPE_SEARCH][google.cloud.retail.v2.SolutionType.SOLUTION_TYPE_SEARCH].
///
/// [google.cloud.retail.v2.Control]: <doc:Control>
/// [google.cloud.retail.v2.SolutionType.SOLUTION_TYPE_SEARCH]: <doc:SolutionType/search>
public struct Rule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The condition that triggers the rule.
  /// If the condition is empty, the rule will always apply.
  public var condition: Condition? = nil

  /// An action must be provided.
  public var action: ActionOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Rule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Rule().with { $0.boostAction = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let boostAction = CodingKeys(stringValue: "boostAction")
    static let redirectAction = CodingKeys(stringValue: "redirectAction")
    static let onewaySynonymsAction = CodingKeys(stringValue: "onewaySynonymsAction")
    static let doNotAssociateAction = CodingKeys(stringValue: "doNotAssociateAction")
    static let replacementAction = CodingKeys(stringValue: "replacementAction")
    static let ignoreAction = CodingKeys(stringValue: "ignoreAction")
    static let filterAction = CodingKeys(stringValue: "filterAction")
    static let twowaySynonymsAction = CodingKeys(stringValue: "twowaySynonymsAction")
    static let forceReturnFacetAction = CodingKeys(stringValue: "forceReturnFacetAction")
    static let removeFacetAction = CodingKeys(stringValue: "removeFacetAction")
    static let pinAction = CodingKeys(stringValue: "pinAction")
    static let condition = CodingKeys(stringValue: "condition")

    static let _knownKeys: Set<Swift.String> = [
      "boostAction",
      "redirectAction",
      "onewaySynonymsAction",
      "doNotAssociateAction",
      "replacementAction",
      "ignoreAction",
      "filterAction",
      "twowaySynonymsAction",
      "forceReturnFacetAction",
      "removeFacetAction",
      "pinAction",
      "condition",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.condition = try container.decodeIfPresent(Condition.self, forKey: .condition)

    var action: ActionOneOf? = nil
    let actionCheckAndSet = {
      if action != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'action'"))
      }
      action = $0
    }
    if let boostAction = try container.decodeIfPresent(Rule.BoostAction?.self, forKey: .boostAction)
    {
      try actionCheckAndSet(.boostAction(boostAction))
    }
    if let redirectAction = try container.decodeIfPresent(
      Rule.RedirectAction?.self, forKey: .redirectAction)
    {
      try actionCheckAndSet(.redirectAction(redirectAction))
    }
    if let onewaySynonymsAction = try container.decodeIfPresent(
      Rule.OnewaySynonymsAction?.self, forKey: .onewaySynonymsAction)
    {
      try actionCheckAndSet(.onewaySynonymsAction(onewaySynonymsAction))
    }
    if let doNotAssociateAction = try container.decodeIfPresent(
      Rule.DoNotAssociateAction?.self, forKey: .doNotAssociateAction)
    {
      try actionCheckAndSet(.doNotAssociateAction(doNotAssociateAction))
    }
    if let replacementAction = try container.decodeIfPresent(
      Rule.ReplacementAction?.self, forKey: .replacementAction)
    {
      try actionCheckAndSet(.replacementAction(replacementAction))
    }
    if let ignoreAction = try container.decodeIfPresent(
      Rule.IgnoreAction?.self, forKey: .ignoreAction)
    {
      try actionCheckAndSet(.ignoreAction(ignoreAction))
    }
    if let filterAction = try container.decodeIfPresent(
      Rule.FilterAction?.self, forKey: .filterAction)
    {
      try actionCheckAndSet(.filterAction(filterAction))
    }
    if let twowaySynonymsAction = try container.decodeIfPresent(
      Rule.TwowaySynonymsAction?.self, forKey: .twowaySynonymsAction)
    {
      try actionCheckAndSet(.twowaySynonymsAction(twowaySynonymsAction))
    }
    if let forceReturnFacetAction = try container.decodeIfPresent(
      Rule.ForceReturnFacetAction?.self, forKey: .forceReturnFacetAction)
    {
      try actionCheckAndSet(.forceReturnFacetAction(forceReturnFacetAction))
    }
    if let removeFacetAction = try container.decodeIfPresent(
      Rule.RemoveFacetAction?.self, forKey: .removeFacetAction)
    {
      try actionCheckAndSet(.removeFacetAction(removeFacetAction))
    }
    if let pinAction = try container.decodeIfPresent(Rule.PinAction?.self, forKey: .pinAction) {
      try actionCheckAndSet(.pinAction(pinAction))
    }
    self.action = action
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.condition, forKey: .condition)

    if let choice = self.action {
      switch choice {
      case .boostAction(let value):
        try container.encode(value, forKey: .boostAction)
      case .redirectAction(let value):
        try container.encode(value, forKey: .redirectAction)
      case .onewaySynonymsAction(let value):
        try container.encode(value, forKey: .onewaySynonymsAction)
      case .doNotAssociateAction(let value):
        try container.encode(value, forKey: .doNotAssociateAction)
      case .replacementAction(let value):
        try container.encode(value, forKey: .replacementAction)
      case .ignoreAction(let value):
        try container.encode(value, forKey: .ignoreAction)
      case .filterAction(let value):
        try container.encode(value, forKey: .filterAction)
      case .twowaySynonymsAction(let value):
        try container.encode(value, forKey: .twowaySynonymsAction)
      case .forceReturnFacetAction(let value):
        try container.encode(value, forKey: .forceReturnFacetAction)
      case .removeFacetAction(let value):
        try container.encode(value, forKey: .removeFacetAction)
      case .pinAction(let value):
        try container.encode(value, forKey: .pinAction)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A boost action to apply to results matching condition specified above.
  public struct BoostAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Strength of the condition boost, which must be in [-1, 1]. Negative
    /// boost means demotion. Default is 0.0.
    ///
    /// Setting to 1.0 gives the item a big promotion. However, it does not
    /// necessarily mean that the boosted item will be the top result at all
    /// times, nor that other items will be excluded. Results could still be
    /// shown even when none of them matches the condition. And results that
    /// are significantly more relevant to the search query can still trump
    /// your heavily favored but irrelevant items.
    ///
    /// Setting to -1.0 gives the item a big demotion. However, results that
    /// are deeply relevant might still be shown. The item will have an
    /// upstream battle to get a fairly high ranking, but it is not blocked out
    /// completely.
    ///
    /// Setting to 0.0 means no boost applied. The boosting condition is
    /// ignored.
    public var boost: Swift.Float = Swift.Float()

    /// The filter can have a max size of 5000 characters.
    /// An expression which specifies which products to apply an action to.
    /// The syntax and supported fields are the same as a filter expression. See
    /// [SearchRequest.filter][google.cloud.retail.v2.SearchRequest.filter] for
    /// detail syntax and limitations.
    ///
    /// Examples:
    ///
    /// * To boost products with product ID "product_1" or "product_2", and
    /// color
    ///   "Red" or "Blue":<br>
    ///   *(id: ANY("product_1", "product_2"))<br>*
    ///   *AND<br>*
    ///   *(colorFamilies: ANY("Red", "Blue"))<br>*
    ///
    /// [google.cloud.retail.v2.SearchRequest.filter]: <doc:SearchRequest/filter>
    public var productsFilter: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `BoostAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BoostAction().with { $0.boost = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let boost = CodingKeys(stringValue: "boost")
      static let productsFilter = CodingKeys(stringValue: "productsFilter")

      static let _knownKeys: Set<Swift.String> = [
        "boost",
        "productsFilter",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .boost) {
        self.boost = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .productsFilter) {
        self.productsFilter = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.boost, forKey: .boost)
      try container.encode(self.productsFilter, forKey: .productsFilter)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Rule.BoostAction"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// * Rule Condition:
  ///     - No
  ///     [Condition.query_terms][google.cloud.retail.v2.Condition.query_terms]
  ///     provided is a global match.
  ///     - 1 or more
  ///     [Condition.query_terms][google.cloud.retail.v2.Condition.query_terms]
  ///     provided are combined with OR operator.
  ///
  /// * Action Input: The request query and filter that are applied to the
  /// retrieved products, in addition to any filters already provided with the
  /// SearchRequest. The AND operator is used to combine the query's existing
  /// filters with the filter rule(s). NOTE: May result in 0 results when
  /// filters conflict.
  ///
  /// * Action Result: Filters the returned objects to be ONLY those that passed
  /// the filter.
  ///
  /// [google.cloud.retail.v2.Condition.query_terms]: <doc:Condition/queryTerms>
  public struct FilterAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A filter to apply on the matching condition results. Supported features:
    ///
    /// * [filter][google.cloud.retail.v2.Rule.FilterAction.filter] must be set.
    /// * Filter syntax is identical to
    /// [SearchRequest.filter][google.cloud.retail.v2.SearchRequest.filter]. For
    /// more
    ///   information, see [Filter](/retail/docs/filter-and-order#filter).
    /// * To filter products with product ID "product_1" or "product_2", and
    /// color
    ///   "Red" or "Blue":<br>
    ///   *(id: ANY("product_1", "product_2"))<br>*
    ///   *AND<br>*
    ///   *(colorFamilies: ANY("Red", "Blue"))<br>*
    ///
    /// [google.cloud.retail.v2.Rule.FilterAction.filter]: <doc:Rule/FilterAction/filter>
    /// [google.cloud.retail.v2.SearchRequest.filter]: <doc:SearchRequest/filter>
    public var filter: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FilterAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FilterAction().with { $0.filter = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let filter = CodingKeys(stringValue: "filter")

      static let _knownKeys: Set<Swift.String> = [
        "filter"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
        self.filter = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.filter, forKey: .filter)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Rule.FilterAction"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Redirects a shopper to a specific page.
  ///
  /// * Rule Condition:
  ///   Must specify
  ///   [Condition.query_terms][google.cloud.retail.v2.Condition.query_terms].
  /// * Action Input: Request Query
  /// * Action Result: Redirects shopper to provided uri.
  ///
  /// [google.cloud.retail.v2.Condition.query_terms]: <doc:Condition/queryTerms>
  public struct RedirectAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// URL must have length equal or less than 2000 characters.
    public var redirectUri: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RedirectAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RedirectAction().with { $0.redirectUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let redirectUri = CodingKeys(stringValue: "redirectUri")

      static let _knownKeys: Set<Swift.String> = [
        "redirectUri"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .redirectUri) {
        self.redirectUri = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.redirectUri, forKey: .redirectUri)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Rule.RedirectAction"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Creates a set of terms that will be treated as synonyms of each other.
  /// Example: synonyms of "sneakers" and "shoes":
  ///
  ///  * "sneakers" will use a synonym of "shoes".
  ///  * "shoes" will use a synonym of "sneakers".
  public struct TwowaySynonymsAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Defines a set of synonyms.
    /// Can specify up to 100 synonyms.
    /// Must specify at least 2 synonyms.
    public var synonyms: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TwowaySynonymsAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TwowaySynonymsAction().with { $0.synonyms = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let synonyms = CodingKeys(stringValue: "synonyms")

      static let _knownKeys: Set<Swift.String> = [
        "synonyms"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .synonyms) {
        self.synonyms = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.synonyms, forKey: .synonyms)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Rule.TwowaySynonymsAction"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Maps a set of terms to a set of synonyms.
  /// Set of synonyms will be treated as synonyms of each query term only.
  /// `query_terms` will not be treated as synonyms of each other.
  /// Example: "sneakers" will use a synonym of "shoes".
  /// "shoes" will not use a synonym of "sneakers".
  public struct OnewaySynonymsAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Terms from the search query.
    /// Will treat synonyms as their synonyms.
    /// Not themselves synonyms of the synonyms.
    /// Can specify up to 100 terms.
    public var queryTerms: [Swift.String] = []

    /// Defines a set of synonyms.
    /// Cannot contain duplicates.
    /// Can specify up to 100 synonyms.
    public var synonyms: [Swift.String] = []

    /// Will be [deprecated = true] post migration;
    public var onewayTerms: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `OnewaySynonymsAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OnewaySynonymsAction().with { $0.queryTerms = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let queryTerms = CodingKeys(stringValue: "queryTerms")
      static let synonyms = CodingKeys(stringValue: "synonyms")
      static let onewayTerms = CodingKeys(stringValue: "onewayTerms")

      static let _knownKeys: Set<Swift.String> = [
        "queryTerms",
        "synonyms",
        "onewayTerms",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .queryTerms) {
        self.queryTerms = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .synonyms) {
        self.synonyms = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .onewayTerms) {
        self.onewayTerms = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.queryTerms, forKey: .queryTerms)
      try container.encode(self.synonyms, forKey: .synonyms)
      try container.encode(self.onewayTerms, forKey: .onewayTerms)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Rule.OnewaySynonymsAction"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Prevents `query_term` from being associated with specified terms during
  /// search.
  /// Example: Don't associate "gShoe" and "cheap".
  public struct DoNotAssociateAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Terms from the search query.
    /// Will not consider do_not_associate_terms for search if in search query.
    /// Can specify up to 100 terms.
    public var queryTerms: [Swift.String] = []

    /// Cannot contain duplicates or the query term.
    /// Can specify up to 100 terms.
    public var doNotAssociateTerms: [Swift.String] = []

    /// Will be [deprecated = true] post migration;
    public var terms: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DoNotAssociateAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DoNotAssociateAction().with { $0.queryTerms = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let queryTerms = CodingKeys(stringValue: "queryTerms")
      static let doNotAssociateTerms = CodingKeys(stringValue: "doNotAssociateTerms")
      static let terms = CodingKeys(stringValue: "terms")

      static let _knownKeys: Set<Swift.String> = [
        "queryTerms",
        "doNotAssociateTerms",
        "terms",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .queryTerms) {
        self.queryTerms = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .doNotAssociateTerms)
      {
        self.doNotAssociateTerms = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .terms) {
        self.terms = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.queryTerms, forKey: .queryTerms)
      try container.encode(self.doNotAssociateTerms, forKey: .doNotAssociateTerms)
      try container.encode(self.terms, forKey: .terms)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Rule.DoNotAssociateAction"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Replaces a term in the query. Multiple replacement candidates can be
  /// specified. All `query_terms` will be replaced with the replacement term.
  /// Example: Replace "gShoe" with "google shoe".
  public struct ReplacementAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Terms from the search query.
    /// Will be replaced by replacement term.
    /// Can specify up to 100 terms.
    public var queryTerms: [Swift.String] = []

    /// Term that will be used for replacement.
    public var replacementTerm: Swift.String = Swift.String()

    /// Will be [deprecated = true] post migration;
    public var term: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ReplacementAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReplacementAction().with { $0.queryTerms = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let queryTerms = CodingKeys(stringValue: "queryTerms")
      static let replacementTerm = CodingKeys(stringValue: "replacementTerm")
      static let term = CodingKeys(stringValue: "term")

      static let _knownKeys: Set<Swift.String> = [
        "queryTerms",
        "replacementTerm",
        "term",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .queryTerms) {
        self.queryTerms = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .replacementTerm) {
        self.replacementTerm = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .term) {
        self.term = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.queryTerms, forKey: .queryTerms)
      try container.encode(self.replacementTerm, forKey: .replacementTerm)
      try container.encode(self.term, forKey: .term)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Rule.ReplacementAction"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Prevents a term in the query from being used in search.
  /// Example: Don't search for "shoddy".
  public struct IgnoreAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Terms to ignore in the search query.
    public var ignoreTerms: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IgnoreAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IgnoreAction().with { $0.ignoreTerms = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ignoreTerms = CodingKeys(stringValue: "ignoreTerms")

      static let _knownKeys: Set<Swift.String> = [
        "ignoreTerms"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .ignoreTerms) {
        self.ignoreTerms = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.ignoreTerms, forKey: .ignoreTerms)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Rule.IgnoreAction"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Force returns an attribute/facet in the request around a certain position
  /// or above.
  ///
  /// * Rule Condition:
  ///   Must specify non-empty
  ///   [Condition.query_terms][google.cloud.retail.v2.Condition.query_terms]
  ///   (for search only) or
  ///   [Condition.page_categories][google.cloud.retail.v2.Condition.page_categories]
  ///   (for browse only), but can't specify both.
  ///
  /// * Action Inputs: attribute name, position
  ///
  /// * Action Result: Will force return a facet key around a certain position
  /// or above if the condition is satisfied.
  ///
  /// Example: Suppose the query is "shoes", the
  /// [Condition.query_terms][google.cloud.retail.v2.Condition.query_terms] is
  /// "shoes", the
  /// [ForceReturnFacetAction.FacetPositionAdjustment.attribute_name][google.cloud.retail.v2.Rule.ForceReturnFacetAction.FacetPositionAdjustment.attribute_name]
  /// is "size" and the
  /// [ForceReturnFacetAction.FacetPositionAdjustment.position][google.cloud.retail.v2.Rule.ForceReturnFacetAction.FacetPositionAdjustment.position]
  /// is 8.
  ///
  /// Two cases: a) The facet key "size" is not already in the top 8 slots, then
  /// the facet "size" will appear at a position close to 8. b) The facet key
  /// "size" in among the top 8 positions in the request, then it will stay at
  /// its current rank.
  ///
  /// [google.cloud.retail.v2.Condition.page_categories]: <doc:Condition/pageCategories>
  /// [google.cloud.retail.v2.Condition.query_terms]: <doc:Condition/queryTerms>
  /// [google.cloud.retail.v2.Rule.ForceReturnFacetAction.FacetPositionAdjustment.attribute_name]: <doc:Rule/ForceReturnFacetAction/FacetPositionAdjustment/attributeName>
  /// [google.cloud.retail.v2.Rule.ForceReturnFacetAction.FacetPositionAdjustment.position]: <doc:Rule/ForceReturnFacetAction/FacetPositionAdjustment/position>
  public struct ForceReturnFacetAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Each instance corresponds to a force return attribute for the given
    /// condition. There can't be more 15 instances here.
    public var facetPositionAdjustments: [Rule.ForceReturnFacetAction.FacetPositionAdjustment] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ForceReturnFacetAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ForceReturnFacetAction().with { $0.facetPositionAdjustments = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let facetPositionAdjustments = CodingKeys(stringValue: "facetPositionAdjustments")

      static let _knownKeys: Set<Swift.String> = [
        "facetPositionAdjustments"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [Rule.ForceReturnFacetAction.FacetPositionAdjustment].self,
        forKey: .facetPositionAdjustments)
      {
        self.facetPositionAdjustments = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.facetPositionAdjustments, forKey: .facetPositionAdjustments)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Each facet position adjustment consists of a single attribute name (i.e.
    /// facet key) along with a specified position.
    public struct FacetPositionAdjustment: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The attribute name to force return as a facet. Each attribute name
      /// should be a valid attribute name, be non-empty and contain at most 80
      /// characters long.
      public var attributeName: Swift.String = Swift.String()

      /// This is the position in the request as explained above. It should be
      /// strictly positive be at most 100.
      public var position: Swift.Int32 = Swift.Int32()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `FacetPositionAdjustment`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = FacetPositionAdjustment().with { $0.attributeName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let attributeName = CodingKeys(stringValue: "attributeName")
        static let position = CodingKeys(stringValue: "position")

        static let _knownKeys: Set<Swift.String> = [
          "attributeName",
          "position",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .attributeName) {
          self.attributeName = value
        }
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .position) {
          self.position = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.attributeName, forKey: .attributeName)
        try container.encode(self.position, forKey: .position)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.retail.v2.Rule.ForceReturnFacetAction.FacetPositionAdjustment"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Rule.ForceReturnFacetAction"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Removes an attribute/facet in the request if is present.
  ///
  /// * Rule Condition:
  ///   Must specify non-empty
  ///   [Condition.query_terms][google.cloud.retail.v2.Condition.query_terms]
  ///   (for search only) or
  ///   [Condition.page_categories][google.cloud.retail.v2.Condition.page_categories]
  ///   (for browse only), but can't specify both.
  ///
  /// * Action Input: attribute name
  ///
  /// * Action Result: Will remove the attribute (as a facet) from the request
  /// if it is present.
  ///
  /// Example: Suppose the query is "shoes", the
  /// [Condition.query_terms][google.cloud.retail.v2.Condition.query_terms] is
  /// "shoes" and the attribute name "size", then facet key "size" will be
  /// removed from the request (if it is present).
  ///
  /// [google.cloud.retail.v2.Condition.page_categories]: <doc:Condition/pageCategories>
  /// [google.cloud.retail.v2.Condition.query_terms]: <doc:Condition/queryTerms>
  public struct RemoveFacetAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The attribute names (i.e. facet keys) to remove from the dynamic facets
    /// (if present in the request). There can't be more 3 attribute names.
    /// Each attribute name should be a valid attribute name, be non-empty and
    /// contain at most 80 characters.
    public var attributeNames: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RemoveFacetAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RemoveFacetAction().with { $0.attributeNames = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let attributeNames = CodingKeys(stringValue: "attributeNames")

      static let _knownKeys: Set<Swift.String> = [
        "attributeNames"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .attributeNames) {
        self.attributeNames = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.attributeNames, forKey: .attributeNames)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Rule.RemoveFacetAction"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Pins one or more specified products to a specific position in the
  /// results.
  ///
  /// * Rule Condition:
  ///   Must specify non-empty
  ///   [Condition.query_terms][google.cloud.retail.v2.Condition.query_terms]
  ///   (for search only) or
  ///   [Condition.page_categories][google.cloud.retail.v2.Condition.page_categories]
  ///   (for browse only), but can't specify both.
  ///
  /// * Action Input: mapping of `[pin_position, product_id]` pairs (pin position
  /// uses 1-based indexing).
  ///
  /// * Action Result: Will pin products with matching ids to the position
  /// specified in the final result order.
  ///
  /// Example: Suppose the query is `shoes`, the
  /// [Condition.query_terms][google.cloud.retail.v2.Condition.query_terms] is
  /// `shoes` and the pin_map has `{1, "pid1"}`, then product with `pid1` will be
  /// pinned to the top position in the final results.
  ///
  /// If multiple PinActions are matched to a single request the actions will
  /// be processed from most to least recently updated.
  ///
  /// Pins to positions larger than the max allowed page size of 120 are not
  /// allowed.
  ///
  /// [google.cloud.retail.v2.Condition.page_categories]: <doc:Condition/pageCategories>
  /// [google.cloud.retail.v2.Condition.query_terms]: <doc:Condition/queryTerms>
  public struct PinAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. A map of positions to product_ids.
    ///
    /// Partial matches per action are allowed, if a certain position in the map
    /// is already filled that `[position, product_id]` pair will be ignored
    /// but the rest may still be applied. This case will only occur if multiple
    /// pin actions are matched to a single request, as the map guarantees that
    /// pin positions are unique within the same action.
    ///
    /// Duplicate product_ids are not permitted within a single pin map.
    ///
    /// The max size of this map is 120, equivalent to the max [request page
    /// size](https://cloud.google.com/retail/docs/reference/rest/v2/projects.locations.catalogs.placements/search#request-body).
    public var pinMap: [Swift.Int64: Swift.String] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PinAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PinAction().with { $0.pinMap = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let pinMap = CodingKeys(stringValue: "pinMap")

      static let _knownKeys: Set<Swift.String> = [
        "pinMap"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let stringKeyed = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .pinMap)
      {
        let tuples = try stringKeyed.lazy.map {
          (key, value) throws -> (Swift.Int64, Swift.String) in
          guard let newKey = Swift.Int64(key) else {
            throw DecodingError.typeMismatch(
              Swift.Int64.self,
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Incorrect type for map key 'pinMap'"))
          }
          return (newKey, value)
        }
        self.pinMap = Dictionary(uniqueKeysWithValues: tuples)
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      do {
        let stringKeyed = Dictionary(
          uniqueKeysWithValues: self.pinMap.lazy.map { (Swift.String($0), $1) }
        )
        try container.encode(stringKeyed, forKey: .pinMap)
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.Rule.PinAction"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// An action must be provided.
  public enum ActionOneOf: Codable, Equatable, Sendable {
    /// A boost action.
    indirect case boostAction(Rule.BoostAction?)
    /// Redirects a shopper to a specific page.
    indirect case redirectAction(Rule.RedirectAction?)
    /// Treats specific term as a synonym with a group of terms.
    /// Group of terms will not be treated as synonyms with the specific term.
    indirect case onewaySynonymsAction(Rule.OnewaySynonymsAction?)
    /// Prevents term from being associated with other terms.
    indirect case doNotAssociateAction(Rule.DoNotAssociateAction?)
    /// Replaces specific terms in the query.
    indirect case replacementAction(Rule.ReplacementAction?)
    /// Ignores specific terms from query during search.
    indirect case ignoreAction(Rule.IgnoreAction?)
    /// Filters results.
    indirect case filterAction(Rule.FilterAction?)
    /// Treats a set of terms as synonyms of one another.
    indirect case twowaySynonymsAction(Rule.TwowaySynonymsAction?)
    /// Force returns an attribute as a facet in the request.
    indirect case forceReturnFacetAction(Rule.ForceReturnFacetAction?)
    /// Remove an attribute as a facet in the request (if present).
    indirect case removeFacetAction(Rule.RemoveFacetAction?)
    /// Pins one or more specified products to a specific position in the
    /// results.
    indirect case pinAction(Rule.PinAction?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.Rule"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
