// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Safety settings.
public struct SafetySetting: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Harm category.
  public var category: HarmCategory = HarmCategory()

  /// The harm block threshold.
  public var threshold: SafetySetting.HarmBlockThreshold = SafetySetting.HarmBlockThreshold()

  /// Optional. Specify if the threshold is used for probability or severity
  /// score. If not specified, the threshold is used for probability score.
  public var method: SafetySetting.HarmBlockMethod = SafetySetting.HarmBlockMethod()

  /// Initialize a new instance of `SafetySetting`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SafetySetting().with { $0.category = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Probability based thresholds levels for blocking.
  public enum HarmBlockThreshold: Codable, Equatable, Sendable {
    /// Unspecified harm block threshold.
    case unspecified
    /// Block low threshold and above (i.e. block more).
    case blockLowAndAbove
    /// Block medium threshold and above.
    case blockMediumAndAbove
    /// Block only high threshold (i.e. block less).
    case blockOnlyHigh
    /// Block none.
    case blockNone
    /// Turn off the safety filter.
    case off
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .blockLowAndAbove: return 1
      case .blockMediumAndAbove: return 2
      case .blockOnlyHigh: return 3
      case .blockNone: return 4
      case .off: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "HARM_BLOCK_THRESHOLD_UNSPECIFIED"
      case .blockLowAndAbove: return "BLOCK_LOW_AND_ABOVE"
      case .blockMediumAndAbove: return "BLOCK_MEDIUM_AND_ABOVE"
      case .blockOnlyHigh: return "BLOCK_ONLY_HIGH"
      case .blockNone: return "BLOCK_NONE"
      case .off: return "OFF"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HarmBlockThreshold/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HARM_BLOCK_THRESHOLD_UNSPECIFIED": self = .unspecified
      case "BLOCK_LOW_AND_ABOVE": self = .blockLowAndAbove
      case "BLOCK_MEDIUM_AND_ABOVE": self = .blockMediumAndAbove
      case "BLOCK_ONLY_HIGH": self = .blockOnlyHigh
      case "BLOCK_NONE": self = .blockNone
      case "OFF": self = .off
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HarmBlockThreshold/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .blockLowAndAbove
      case 2: self = .blockMediumAndAbove
      case 3: self = .blockOnlyHigh
      case 4: self = .blockNone
      case 5: self = .off
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .blockLowAndAbove: return try container.encode(1)
      case .blockMediumAndAbove: return try container.encode(2)
      case .blockOnlyHigh: return try container.encode(3)
      case .blockNone: return try container.encode(4)
      case .off: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Probability vs severity.
  public enum HarmBlockMethod: Codable, Equatable, Sendable {
    /// The harm block method is unspecified.
    case unspecified
    /// The harm block method uses both probability and severity scores.
    case severity
    /// The harm block method uses the probability score.
    case probability
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .severity: return 1
      case .probability: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "HARM_BLOCK_METHOD_UNSPECIFIED"
      case .severity: return "SEVERITY"
      case .probability: return "PROBABILITY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HarmBlockMethod/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HARM_BLOCK_METHOD_UNSPECIFIED": self = .unspecified
      case "SEVERITY": self = .severity
      case "PROBABILITY": self = .probability
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HarmBlockMethod/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .severity
      case 2: self = .probability
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .severity: return try container.encode(1)
      case .probability: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.SafetySetting"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
