// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for
/// [SearchService.Search][google.cloud.retail.v2.SearchService.Search] method.
///
/// [google.cloud.retail.v2.SearchService.Search]: <doc:SearchServiceClient/search(request:options:)>
public struct SearchResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A list of matched items. The order represents the ranking.
  public var results: [SearchResponse.SearchResult] = []

  /// Results of facets requested by user.
  public var facets: [SearchResponse.Facet] = []

  /// The estimated total count of matched items irrespective of pagination. The
  /// count of [results][google.cloud.retail.v2.SearchResponse.results] returned
  /// by pagination may be less than the
  /// [total_size][google.cloud.retail.v2.SearchResponse.total_size] that
  /// matches.
  ///
  /// [google.cloud.retail.v2.SearchResponse.results]: <doc:SearchResponse/results>
  /// [google.cloud.retail.v2.SearchResponse.total_size]: <doc:SearchResponse/totalSize>
  public var totalSize: Swift.Int32 = Swift.Int32()

  /// Contains the spell corrected query, if found. If the spell correction type
  /// is AUTOMATIC, then the search results are based on corrected_query.
  /// Otherwise the original query is used for search.
  public var correctedQuery: Swift.String = Swift.String()

  /// A unique search token. This should be included in the
  /// [UserEvent][google.cloud.retail.v2.UserEvent] logs resulting from this
  /// search, which enables accurate attribution of search model performance.
  ///
  /// [google.cloud.retail.v2.UserEvent]: <doc:UserEvent>
  public var attributionToken: Swift.String = Swift.String()

  /// A token that can be sent as
  /// [SearchRequest.page_token][google.cloud.retail.v2.SearchRequest.page_token]
  /// to retrieve the next page. If this field is omitted, there are no
  /// subsequent pages.
  ///
  /// [google.cloud.retail.v2.SearchRequest.page_token]: <doc:SearchRequest/pageToken>
  public var nextPageToken: Swift.String = Swift.String()

  /// Query expansion information for the returned results.
  public var queryExpansionInfo: SearchResponse.QueryExpansionInfo? = nil

  /// The URI of a customer-defined redirect page. If redirect action is
  /// triggered, no search is performed, and only
  /// [redirect_uri][google.cloud.retail.v2.SearchResponse.redirect_uri] and
  /// [attribution_token][google.cloud.retail.v2.SearchResponse.attribution_token]
  /// are set in the response.
  ///
  /// [google.cloud.retail.v2.SearchResponse.attribution_token]: <doc:SearchResponse/attributionToken>
  /// [google.cloud.retail.v2.SearchResponse.redirect_uri]: <doc:SearchResponse/redirectUri>
  public var redirectUri: Swift.String = Swift.String()

  /// The fully qualified resource name of applied
  /// [controls](https://cloud.google.com/retail/docs/serving-control-rules).
  public var appliedControls: [Swift.String] = []

  /// Metadata for pin controls which were applicable to the request.
  /// This contains two map fields, one for all matched pins and one for pins
  /// which were matched but not applied.
  ///
  /// The two maps are keyed by pin position, and the values are the product ids
  /// which were matched to that pin.
  public var pinControlMetadata: PinControlMetadata? = nil

  /// The invalid
  /// [SearchRequest.BoostSpec.condition_boost_specs][google.cloud.retail.v2.SearchRequest.BoostSpec.condition_boost_specs]
  /// that are not applied during serving.
  ///
  /// [google.cloud.retail.v2.SearchRequest.BoostSpec.condition_boost_specs]: <doc:SearchRequest/BoostSpec/conditionBoostSpecs>
  public var invalidConditionBoostSpecs: [SearchRequest.BoostSpec.ConditionBoostSpec] = []

  /// Metadata related to A/B testing experiment associated with this
  /// response. Only exists when an experiment is triggered.
  public var experimentInfo: [ExperimentInfo] = []

  /// This field specifies all related information that is needed on client
  /// side for UI rendering of conversational retail search.
  public var conversationalSearchResult: SearchResponse.ConversationalSearchResult? = nil

  /// This field specifies all related information for tile navigation that will
  /// be used in client side.
  public var tileNavigationResult: SearchResponse.TileNavigationResult? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SearchResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchResponse().with { $0.results = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let results = CodingKeys(stringValue: "results")
    static let facets = CodingKeys(stringValue: "facets")
    static let totalSize = CodingKeys(stringValue: "totalSize")
    static let correctedQuery = CodingKeys(stringValue: "correctedQuery")
    static let attributionToken = CodingKeys(stringValue: "attributionToken")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let queryExpansionInfo = CodingKeys(stringValue: "queryExpansionInfo")
    static let redirectUri = CodingKeys(stringValue: "redirectUri")
    static let appliedControls = CodingKeys(stringValue: "appliedControls")
    static let pinControlMetadata = CodingKeys(stringValue: "pinControlMetadata")
    static let invalidConditionBoostSpecs = CodingKeys(stringValue: "invalidConditionBoostSpecs")
    static let experimentInfo = CodingKeys(stringValue: "experimentInfo")
    static let conversationalSearchResult = CodingKeys(stringValue: "conversationalSearchResult")
    static let tileNavigationResult = CodingKeys(stringValue: "tileNavigationResult")

    static let _knownKeys: Set<Swift.String> = [
      "results",
      "facets",
      "totalSize",
      "correctedQuery",
      "attributionToken",
      "nextPageToken",
      "queryExpansionInfo",
      "redirectUri",
      "appliedControls",
      "pinControlMetadata",
      "invalidConditionBoostSpecs",
      "experimentInfo",
      "conversationalSearchResult",
      "tileNavigationResult",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [SearchResponse.SearchResult].self, forKey: .results)
    {
      self.results = value
    }
    if let value = try container.decodeIfPresent([SearchResponse.Facet].self, forKey: .facets) {
      self.facets = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalSize) {
      self.totalSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .correctedQuery) {
      self.correctedQuery = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .attributionToken) {
      self.attributionToken = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    self.queryExpansionInfo = try container.decodeIfPresent(
      SearchResponse.QueryExpansionInfo.self, forKey: .queryExpansionInfo)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .redirectUri) {
      self.redirectUri = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .appliedControls) {
      self.appliedControls = value
    }
    self.pinControlMetadata = try container.decodeIfPresent(
      PinControlMetadata.self, forKey: .pinControlMetadata)
    if let value = try container.decodeIfPresent(
      [SearchRequest.BoostSpec.ConditionBoostSpec].self, forKey: .invalidConditionBoostSpecs)
    {
      self.invalidConditionBoostSpecs = value
    }
    if let value = try container.decodeIfPresent([ExperimentInfo].self, forKey: .experimentInfo) {
      self.experimentInfo = value
    }
    self.conversationalSearchResult = try container.decodeIfPresent(
      SearchResponse.ConversationalSearchResult.self, forKey: .conversationalSearchResult)
    self.tileNavigationResult = try container.decodeIfPresent(
      SearchResponse.TileNavigationResult.self, forKey: .tileNavigationResult)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.results, forKey: .results)
    try container.encode(self.facets, forKey: .facets)
    try container.encode(self.totalSize, forKey: .totalSize)
    try container.encode(self.correctedQuery, forKey: .correctedQuery)
    try container.encode(self.attributionToken, forKey: .attributionToken)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encodeIfPresent(self.queryExpansionInfo, forKey: .queryExpansionInfo)
    try container.encode(self.redirectUri, forKey: .redirectUri)
    try container.encode(self.appliedControls, forKey: .appliedControls)
    try container.encodeIfPresent(self.pinControlMetadata, forKey: .pinControlMetadata)
    try container.encode(self.invalidConditionBoostSpecs, forKey: .invalidConditionBoostSpecs)
    try container.encode(self.experimentInfo, forKey: .experimentInfo)
    try container.encodeIfPresent(
      self.conversationalSearchResult, forKey: .conversationalSearchResult)
    try container.encodeIfPresent(self.tileNavigationResult, forKey: .tileNavigationResult)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents the search results.
  public struct SearchResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// [Product.id][google.cloud.retail.v2.Product.id] of the searched
    /// [Product][google.cloud.retail.v2.Product].
    ///
    /// [google.cloud.retail.v2.Product]: <doc:Product>
    /// [google.cloud.retail.v2.Product.id]: <doc:Product/id>
    public var id: Swift.String = Swift.String()

    /// The product data snippet in the search response. Only
    /// [Product.name][google.cloud.retail.v2.Product.name] is guaranteed to be
    /// populated.
    ///
    /// [Product.variants][google.cloud.retail.v2.Product.variants] contains the
    /// product variants that match the search query. If there are multiple
    /// product variants matching the query, top 5 most relevant product variants
    /// are returned and ordered by relevancy.
    ///
    /// If relevancy can be deternmined, use
    /// [matching_variant_fields][google.cloud.retail.v2.SearchResponse.SearchResult.matching_variant_fields]
    /// to look up matched product variants fields. If relevancy cannot be
    /// determined, e.g. when searching "shoe" all products in a shoe product can
    /// be a match, 5 product variants are returned but order is meaningless.
    ///
    /// [google.cloud.retail.v2.Product.name]: <doc:Product/name>
    /// [google.cloud.retail.v2.Product.variants]: <doc:Product/variants>
    /// [google.cloud.retail.v2.SearchResponse.SearchResult.matching_variant_fields]: <doc:SearchResponse/SearchResult/matchingVariantFields>
    public var product: Product? = nil

    /// The count of matched
    /// [variant][google.cloud.retail.v2.Product.Type.VARIANT]
    /// [Product][google.cloud.retail.v2.Product]s.
    ///
    /// [google.cloud.retail.v2.Product]: <doc:Product>
    /// [google.cloud.retail.v2.Product.Type.VARIANT]: <doc:Product/Type_/variant>
    public var matchingVariantCount: Swift.Int32 = Swift.Int32()

    /// If a [variant][google.cloud.retail.v2.Product.Type.VARIANT]
    /// [Product][google.cloud.retail.v2.Product] matches the search query, this
    /// map indicates which [Product][google.cloud.retail.v2.Product] fields are
    /// matched. The key is the
    /// [Product.name][google.cloud.retail.v2.Product.name], the value is a field
    /// mask of the matched [Product][google.cloud.retail.v2.Product] fields. If
    /// matched attributes cannot be determined, this map will be empty.
    ///
    /// For example, a key "sku1" with field mask
    /// "products.color_info" indicates there is a match between
    /// "sku1" [ColorInfo][google.cloud.retail.v2.ColorInfo] and the query.
    ///
    /// [google.cloud.retail.v2.ColorInfo]: <doc:ColorInfo>
    /// [google.cloud.retail.v2.Product]: <doc:Product>
    /// [google.cloud.retail.v2.Product.Type.VARIANT]: <doc:Product/Type_/variant>
    /// [google.cloud.retail.v2.Product.name]: <doc:Product/name>
    public var matchingVariantFields: [Swift.String: GoogleWKT.WKTFieldMask] = [:]

    /// The rollup matching
    /// [variant][google.cloud.retail.v2.Product.Type.VARIANT]
    /// [Product][google.cloud.retail.v2.Product] attributes. The key is one of
    /// the
    /// [SearchRequest.variant_rollup_keys][google.cloud.retail.v2.SearchRequest.variant_rollup_keys].
    /// The values are the merged and de-duplicated
    /// [Product][google.cloud.retail.v2.Product] attributes. Notice that the
    /// rollup values are respect filter. For example, when filtering by
    /// "colorFamilies:ANY(\"red\")" and rollup "colorFamilies", only "red" is
    /// returned.
    ///
    /// For textual and numerical attributes, the rollup values is a list of
    /// string or double values with type
    /// [google.protobuf.ListValue][google.protobuf.ListValue]. For example, if
    /// there are two variants with colors "red" and "blue", the rollup values
    /// are
    ///
    ///     { key: "colorFamilies"
    ///       value {
    ///         list_value {
    ///           values { string_value: "red" }
    ///           values { string_value: "blue" }
    ///          }
    ///       }
    ///     }
    ///
    /// For [FulfillmentInfo][google.cloud.retail.v2.FulfillmentInfo], the rollup
    /// values is a double value with type
    /// [google.protobuf.Value][google.protobuf.Value]. For example,
    /// `{key: "pickupInStore.store1" value { number_value: 10 }}` means a there
    /// are 10 variants in this product are available in the store "store1".
    ///
    /// [google.cloud.retail.v2.FulfillmentInfo]: <doc:FulfillmentInfo>
    /// [google.cloud.retail.v2.Product]: <doc:Product>
    /// [google.cloud.retail.v2.Product.Type.VARIANT]: <doc:Product/Type_/variant>
    /// [google.cloud.retail.v2.SearchRequest.variant_rollup_keys]: <doc:SearchRequest/variantRollupKeys>
    /// [google.protobuf.ListValue]: https://www.google.com/search?q=Swift+google.protobuf+GoogleWKT.WKTListValue
    /// [google.protobuf.Value]: https://www.google.com/search?q=Swift+google.protobuf+GoogleWKT.WKTValue
    public var variantRollupValues: [Swift.String: GoogleWKT.WKTValue] = [:]

    /// Specifies previous events related to this product for this user based on
    /// [UserEvent][google.cloud.retail.v2.UserEvent] with same
    /// [SearchRequest.visitor_id][google.cloud.retail.v2.SearchRequest.visitor_id]
    /// or [UserInfo.user_id][google.cloud.retail.v2.UserInfo.user_id].
    ///
    /// This is set only when
    /// [SearchRequest.PersonalizationSpec.mode][google.cloud.retail.v2.SearchRequest.PersonalizationSpec.mode]
    /// is
    /// [SearchRequest.PersonalizationSpec.Mode.AUTO][google.cloud.retail.v2.SearchRequest.PersonalizationSpec.Mode.AUTO].
    ///
    /// Possible values:
    ///
    /// * `purchased`: Indicates that this product has been purchased before.
    ///
    /// [google.cloud.retail.v2.SearchRequest.PersonalizationSpec.Mode.AUTO]: <doc:SearchRequest/PersonalizationSpec/Mode/auto>
    /// [google.cloud.retail.v2.SearchRequest.PersonalizationSpec.mode]: <doc:SearchRequest/PersonalizationSpec/mode>
    /// [google.cloud.retail.v2.SearchRequest.visitor_id]: <doc:SearchRequest/visitorId>
    /// [google.cloud.retail.v2.UserEvent]: <doc:UserEvent>
    /// [google.cloud.retail.v2.UserInfo.user_id]: <doc:UserInfo/userId>
    public var personalLabels: [Swift.String] = []

    /// Google provided available scores.
    public var modelScores: [Swift.String: DoubleList] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SearchResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SearchResult().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let id = CodingKeys(stringValue: "id")
      static let product = CodingKeys(stringValue: "product")
      static let matchingVariantCount = CodingKeys(stringValue: "matchingVariantCount")
      static let matchingVariantFields = CodingKeys(stringValue: "matchingVariantFields")
      static let variantRollupValues = CodingKeys(stringValue: "variantRollupValues")
      static let personalLabels = CodingKeys(stringValue: "personalLabels")
      static let modelScores = CodingKeys(stringValue: "modelScores")

      static let _knownKeys: Set<Swift.String> = [
        "id",
        "product",
        "matchingVariantCount",
        "matchingVariantFields",
        "variantRollupValues",
        "personalLabels",
        "modelScores",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      self.product = try container.decodeIfPresent(Product.self, forKey: .product)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .matchingVariantCount)
      {
        self.matchingVariantCount = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: GoogleWKT.WKTFieldMask].self, forKey: .matchingVariantFields)
      {
        self.matchingVariantFields = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: GoogleWKT.WKTValue].self, forKey: .variantRollupValues)
      {
        self.variantRollupValues = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .personalLabels) {
        self.personalLabels = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: DoubleList].self, forKey: .modelScores)
      {
        self.modelScores = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.id, forKey: .id)
      try container.encodeIfPresent(self.product, forKey: .product)
      try container.encode(self.matchingVariantCount, forKey: .matchingVariantCount)
      try container.encode(self.matchingVariantFields, forKey: .matchingVariantFields)
      try container.encode(self.variantRollupValues, forKey: .variantRollupValues)
      try container.encode(self.personalLabels, forKey: .personalLabels)
      try container.encode(self.modelScores, forKey: .modelScores)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.SearchResponse.SearchResult"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A facet result.
  public struct Facet: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The key for this facet. E.g., "colorFamilies" or "price" or
    /// "attributes.attr1".
    public var key: Swift.String = Swift.String()

    /// The facet values for this field.
    public var values: [SearchResponse.Facet.FacetValue] = []

    /// Whether the facet is dynamically generated.
    public var dynamicFacet: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Facet`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Facet().with { $0.key = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let key = CodingKeys(stringValue: "key")
      static let values = CodingKeys(stringValue: "values")
      static let dynamicFacet = CodingKeys(stringValue: "dynamicFacet")

      static let _knownKeys: Set<Swift.String> = [
        "key",
        "values",
        "dynamicFacet",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .key) {
        self.key = value
      }
      if let value = try container.decodeIfPresent(
        [SearchResponse.Facet.FacetValue].self, forKey: .values)
      {
        self.values = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .dynamicFacet) {
        self.dynamicFacet = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.key, forKey: .key)
      try container.encode(self.values, forKey: .values)
      try container.encode(self.dynamicFacet, forKey: .dynamicFacet)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// A facet value which contains value names and their count.
    public struct FacetValue: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Number of items that have this facet value.
      public var count: Swift.Int64 = Swift.Int64()

      /// The minimum value in the
      /// [FacetValue.interval][google.cloud.retail.v2.SearchResponse.Facet.FacetValue.interval].
      /// Only supported on numerical facets and returned if
      /// [SearchRequest.FacetSpec.FacetKey.return_min_max][google.cloud.retail.v2.SearchRequest.FacetSpec.FacetKey.return_min_max]
      /// is true.
      ///
      /// [google.cloud.retail.v2.SearchRequest.FacetSpec.FacetKey.return_min_max]: <doc:SearchRequest/FacetSpec/FacetKey/returnMinMax>
      /// [google.cloud.retail.v2.SearchResponse.Facet.FacetValue.interval]: <doc:SearchResponse/Facet/FacetValue/FacetValueOneOf/interval(_:)>
      public var minValue: Swift.Double = Swift.Double()

      /// The maximum value in the
      /// [FacetValue.interval][google.cloud.retail.v2.SearchResponse.Facet.FacetValue.interval].
      /// Only supported on numerical facets and returned if
      /// [SearchRequest.FacetSpec.FacetKey.return_min_max][google.cloud.retail.v2.SearchRequest.FacetSpec.FacetKey.return_min_max]
      /// is true.
      ///
      /// [google.cloud.retail.v2.SearchRequest.FacetSpec.FacetKey.return_min_max]: <doc:SearchRequest/FacetSpec/FacetKey/returnMinMax>
      /// [google.cloud.retail.v2.SearchResponse.Facet.FacetValue.interval]: <doc:SearchResponse/Facet/FacetValue/FacetValueOneOf/interval(_:)>
      public var maxValue: Swift.Double = Swift.Double()

      /// A facet value which contains values.
      public var facetValue: FacetValueOneOf? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `FacetValue`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = FacetValue().with { $0.value = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let value = CodingKeys(stringValue: "value")
        static let interval = CodingKeys(stringValue: "interval")
        static let count = CodingKeys(stringValue: "count")
        static let minValue = CodingKeys(stringValue: "minValue")
        static let maxValue = CodingKeys(stringValue: "maxValue")

        static let _knownKeys: Set<Swift.String> = [
          "value",
          "interval",
          "count",
          "minValue",
          "maxValue",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .count) {
          self.count = value
        }
        if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .minValue) {
          self.minValue = value
        }
        if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .maxValue) {
          self.maxValue = value
        }

        var facetValue: FacetValueOneOf? = nil
        let facetValueCheckAndSet = {
          if facetValue != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'facetValue'"))
          }
          facetValue = $0
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .value) {
          try facetValueCheckAndSet(.value(value))
        }
        if let interval = try container.decodeIfPresent(Interval?.self, forKey: .interval) {
          try facetValueCheckAndSet(.interval(interval))
        }
        self.facetValue = facetValue
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.count, forKey: .count)
        try container.encode(self.minValue, forKey: .minValue)
        try container.encode(self.maxValue, forKey: .maxValue)

        if let choice = self.facetValue {
          switch choice {
          case .value(let value):
            try container.encode(value, forKey: .value)
          case .interval(let value):
            try container.encode(value, forKey: .interval)
          }
        }
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// A facet value which contains values.
      public enum FacetValueOneOf: Codable, Equatable, Sendable {
        /// Text value of a facet, such as "Black" for facet "colorFamilies".
        case value(Swift.String)
        /// Interval value for a facet, such as [10, 20) for facet "price".
        indirect case interval(Interval?)
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.retail.v2.SearchResponse.Facet.FacetValue"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.SearchResponse.Facet"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information describing query expansion including whether expansion has
  /// occurred.
  public struct QueryExpansionInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Bool describing whether query expansion has occurred.
    public var expandedQuery: Swift.Bool = Swift.Bool()

    /// Number of pinned results. This field will only be set when expansion
    /// happens and
    /// [SearchRequest.QueryExpansionSpec.pin_unexpanded_results][google.cloud.retail.v2.SearchRequest.QueryExpansionSpec.pin_unexpanded_results]
    /// is set to true.
    ///
    /// [google.cloud.retail.v2.SearchRequest.QueryExpansionSpec.pin_unexpanded_results]: <doc:SearchRequest/QueryExpansionSpec/pinUnexpandedResults>
    public var pinnedResultCount: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `QueryExpansionInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QueryExpansionInfo().with { $0.expandedQuery = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let expandedQuery = CodingKeys(stringValue: "expandedQuery")
      static let pinnedResultCount = CodingKeys(stringValue: "pinnedResultCount")

      static let _knownKeys: Set<Swift.String> = [
        "expandedQuery",
        "pinnedResultCount",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .expandedQuery) {
        self.expandedQuery = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .pinnedResultCount) {
        self.pinnedResultCount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.expandedQuery, forKey: .expandedQuery)
      try container.encode(self.pinnedResultCount, forKey: .pinnedResultCount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.SearchResponse.QueryExpansionInfo"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// This field specifies all related information that is needed on client
  /// side for UI rendering of conversational retail search.
  public struct ConversationalSearchResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Conversation UUID. This field will be stored in client side storage to
    /// maintain the conversation session with server and will be used for next
    /// search request's
    /// [SearchRequest.ConversationalSearchSpec.conversation_id][google.cloud.retail.v2.SearchRequest.ConversationalSearchSpec.conversation_id]
    /// to restore conversation state in server.
    ///
    /// [google.cloud.retail.v2.SearchRequest.ConversationalSearchSpec.conversation_id]: <doc:SearchRequest/ConversationalSearchSpec/conversationId>
    public var conversationId: Swift.String = Swift.String()

    /// The current refined query for the conversational search. This field
    /// will be used in customer UI that the query in the search bar should be
    /// replaced with the refined query. For example, if
    /// [SearchRequest.query][google.cloud.retail.v2.SearchRequest.query] is
    /// `dress` and next
    /// [SearchRequest.ConversationalSearchSpec.UserAnswer.text_answer][google.cloud.retail.v2.SearchRequest.ConversationalSearchSpec.UserAnswer.text_answer]
    /// is `red color`, which does not match any product attribute value filters,
    /// the refined query will be `dress, red color`.
    ///
    /// [google.cloud.retail.v2.SearchRequest.ConversationalSearchSpec.UserAnswer.text_answer]: <doc:SearchRequest/ConversationalSearchSpec/UserAnswer/TypeOneOf/textAnswer(_:)>
    /// [google.cloud.retail.v2.SearchRequest.query]: <doc:SearchRequest/query>
    public var refinedQuery: Swift.String = Swift.String()

    /// This field is deprecated but will be kept for backward compatibility.
    /// There is expected to have only one additional filter and the value will
    /// be the same to the same as field `additional_filter`.
    @available(*, deprecated)
    public var additionalFilters: [SearchResponse.ConversationalSearchResult.AdditionalFilter] = []

    /// The follow-up question. e.g., `What is the color?`
    public var followupQuestion: Swift.String = Swift.String()

    /// The answer options provided to client for the follow-up question.
    public var suggestedAnswers: [SearchResponse.ConversationalSearchResult.SuggestedAnswer] = []

    /// This is the incremental additional filters implied from the current
    /// user answer. User should add the suggested addition filters to the
    /// previous
    /// [SearchRequest.filter][google.cloud.retail.v2.SearchRequest.filter],  and
    /// use the merged filter in the follow up search request.
    ///
    /// [google.cloud.retail.v2.SearchRequest.filter]: <doc:SearchRequest/filter>
    public var additionalFilter: SearchResponse.ConversationalSearchResult.AdditionalFilter? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConversationalSearchResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConversationalSearchResult().with { $0.conversationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let conversationId = CodingKeys(stringValue: "conversationId")
      static let refinedQuery = CodingKeys(stringValue: "refinedQuery")
      static let additionalFilters = CodingKeys(stringValue: "additionalFilters")
      static let followupQuestion = CodingKeys(stringValue: "followupQuestion")
      static let suggestedAnswers = CodingKeys(stringValue: "suggestedAnswers")
      static let additionalFilter = CodingKeys(stringValue: "additionalFilter")

      static let _knownKeys: Set<Swift.String> = [
        "conversationId",
        "refinedQuery",
        "additionalFilters",
        "followupQuestion",
        "suggestedAnswers",
        "additionalFilter",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .conversationId) {
        self.conversationId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .refinedQuery) {
        self.refinedQuery = value
      }
      if let value = try container.decodeIfPresent(
        [SearchResponse.ConversationalSearchResult.AdditionalFilter].self,
        forKey: .additionalFilters)
      {
        self.additionalFilters = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .followupQuestion) {
        self.followupQuestion = value
      }
      if let value = try container.decodeIfPresent(
        [SearchResponse.ConversationalSearchResult.SuggestedAnswer].self, forKey: .suggestedAnswers)
      {
        self.suggestedAnswers = value
      }
      self.additionalFilter = try container.decodeIfPresent(
        SearchResponse.ConversationalSearchResult.AdditionalFilter.self, forKey: .additionalFilter)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.conversationId, forKey: .conversationId)
      try container.encode(self.refinedQuery, forKey: .refinedQuery)
      try container.encode(self.additionalFilters, forKey: .additionalFilters)
      try container.encode(self.followupQuestion, forKey: .followupQuestion)
      try container.encode(self.suggestedAnswers, forKey: .suggestedAnswers)
      try container.encodeIfPresent(self.additionalFilter, forKey: .additionalFilter)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Suggested answers to the follow-up question.
    public struct SuggestedAnswer: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Product attribute value, including an attribute key and an
      /// attribute value. Other types can be added here in the future.
      public var productAttributeValue: ProductAttributeValue? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `SuggestedAnswer`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SuggestedAnswer().with { $0.productAttributeValue = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let productAttributeValue = CodingKeys(stringValue: "productAttributeValue")

        static let _knownKeys: Set<Swift.String> = [
          "productAttributeValue"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.productAttributeValue = try container.decodeIfPresent(
          ProductAttributeValue.self, forKey: .productAttributeValue)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.productAttributeValue, forKey: .productAttributeValue)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.retail.v2.SearchResponse.ConversationalSearchResult.SuggestedAnswer"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Additional filter that client side need to apply.
    public struct AdditionalFilter: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Product attribute value, including an attribute key and an
      /// attribute value. Other types can be added here in the future.
      public var productAttributeValue: ProductAttributeValue? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `AdditionalFilter`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = AdditionalFilter().with { $0.productAttributeValue = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let productAttributeValue = CodingKeys(stringValue: "productAttributeValue")

        static let _knownKeys: Set<Swift.String> = [
          "productAttributeValue"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.productAttributeValue = try container.decodeIfPresent(
          ProductAttributeValue.self, forKey: .productAttributeValue)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.productAttributeValue, forKey: .productAttributeValue)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.retail.v2.SearchResponse.ConversationalSearchResult.AdditionalFilter"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.SearchResponse.ConversationalSearchResult"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// This field specifies all related information for tile navigation that will
  /// be used in client side.
  public struct TileNavigationResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The current tiles that are used for tile navigation, sorted by
    /// engagement.
    public var tiles: [Tile] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TileNavigationResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TileNavigationResult().with { $0.tiles = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let tiles = CodingKeys(stringValue: "tiles")

      static let _knownKeys: Set<Swift.String> = [
        "tiles"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Tile].self, forKey: .tiles) {
        self.tiles = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.tiles, forKey: .tiles)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.retail.v2.SearchResponse.TileNavigationResult"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.SearchResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension SearchResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [SearchResponse.SearchResult] {
    return self.results
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
