// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message to set a specified branch as new default_branch.
public struct SetDefaultBranchRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Full resource name of the catalog, such as
  /// `projects/*/locations/global/catalogs/default_catalog`.
  public var catalog: Swift.String = Swift.String()

  /// The final component of the resource name of a branch.
  ///
  /// This field must be one of "0", "1" or "2". Otherwise, an INVALID_ARGUMENT
  /// error is returned.
  ///
  /// If there are no sufficient active products in the targeted branch and
  /// [force][google.cloud.retail.v2.SetDefaultBranchRequest.force] is not set, a
  /// FAILED_PRECONDITION error is returned.
  ///
  /// [google.cloud.retail.v2.SetDefaultBranchRequest.force]: <doc:SetDefaultBranchRequest/force>
  public var branchId: Swift.String = Swift.String()

  /// Some note on this request, this can be retrieved by
  /// [CatalogService.GetDefaultBranch][google.cloud.retail.v2.CatalogService.GetDefaultBranch]
  /// before next valid default branch set occurs.
  ///
  /// This field must be a UTF-8 encoded string with a length limit of 1,000
  /// characters. Otherwise, an INVALID_ARGUMENT error is returned.
  ///
  /// [google.cloud.retail.v2.CatalogService.GetDefaultBranch]: <doc:CatalogServiceClient/getDefaultBranch(request:options:)>
  public var note: Swift.String = Swift.String()

  /// If set to true, it permits switching to a branch with
  /// [branch_id][google.cloud.retail.v2.SetDefaultBranchRequest.branch_id] even
  /// if it has no sufficient active products.
  ///
  /// [google.cloud.retail.v2.SetDefaultBranchRequest.branch_id]: <doc:SetDefaultBranchRequest/branchId>
  public var force: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SetDefaultBranchRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SetDefaultBranchRequest().with { $0.catalog = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let catalog = CodingKeys(stringValue: "catalog")
    static let branchId = CodingKeys(stringValue: "branchId")
    static let note = CodingKeys(stringValue: "note")
    static let force = CodingKeys(stringValue: "force")

    static let _knownKeys: Set<Swift.String> = [
      "catalog",
      "branchId",
      "note",
      "force",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .catalog) {
      self.catalog = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .branchId) {
      self.branchId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .note) {
      self.note = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .force) {
      self.force = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.catalog, forKey: .catalog)
    try container.encode(self.branchId, forKey: .branchId)
    try container.encode(self.note, forKey: .note)
    try container.encode(self.force, forKey: .force)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.SetDefaultBranchRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
