// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The input config source for user events.
public struct UserEventInputConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The source of the input.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `UserEventInputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UserEventInputConfig().with { $0.userEventInlineSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case userEventInlineSource = "userEventInlineSource"
    case gcsSource = "gcsSource"
    case bigQuerySource = "bigQuerySource"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let userEventInlineSource = try container.decodeIfPresent(
      UserEventInlineSource?.self, forKey: .userEventInlineSource)
    {
      try sourceCheckAndSet(.userEventInlineSource(userEventInlineSource))
    }
    if let gcsSource = try container.decodeIfPresent(GcsSource?.self, forKey: .gcsSource) {
      try sourceCheckAndSet(.gcsSource(gcsSource))
    }
    if let bigQuerySource = try container.decodeIfPresent(
      BigQuerySource?.self, forKey: .bigQuerySource)
    {
      try sourceCheckAndSet(.bigQuerySource(bigQuerySource))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.source {
      switch choice {
      case .userEventInlineSource(let value):
        try container.encode(value, forKey: .userEventInlineSource)
      case .gcsSource(let value):
        try container.encode(value, forKey: .gcsSource)
      case .bigQuerySource(let value):
        try container.encode(value, forKey: .bigQuerySource)
      }
    }
  }

  /// The source of the input.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Required. The Inline source for the input content for UserEvents.
    indirect case userEventInlineSource(UserEventInlineSource?)
    /// Required. Google Cloud Storage location for the input content.
    indirect case gcsSource(GcsSource?)
    /// Required. BigQuery input source.
    indirect case bigQuerySource(BigQuerySource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.UserEventInputConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
