// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Information of an end user.
public struct UserInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Highly recommended for logged-in users. Unique identifier for logged-in
  /// user, such as a user name. Don't set for anonymous users.
  ///
  /// Always use a hashed value for this ID.
  ///
  /// Don't set the field to the same fixed ID for different users. This mixes
  /// the event history of those users together, which results in degraded
  /// model quality.
  ///
  /// The field must be a UTF-8 encoded string with a length limit of 128
  /// characters. Otherwise, an INVALID_ARGUMENT error is returned.
  public var userId: Swift.String = Swift.String()

  /// The end user's IP address. This field is used to extract location
  /// information for personalization.
  ///
  /// This field must be either an IPv4 address (e.g. "104.133.9.80") or an IPv6
  /// address (e.g. "2001:0db8:85a3:0000:0000:8a2e:0370:7334"). Otherwise, an
  /// INVALID_ARGUMENT error is returned.
  ///
  /// This should not be set when:
  ///
  /// * setting
  /// [SearchRequest.user_info][google.cloud.retail.v2.SearchRequest.user_info].
  /// * using the JavaScript tag in
  /// [UserEventService.CollectUserEvent][google.cloud.retail.v2.UserEventService.CollectUserEvent]
  /// or if
  /// [direct_user_request][google.cloud.retail.v2.UserInfo.direct_user_request]
  /// is set.
  ///
  /// [google.cloud.retail.v2.SearchRequest.user_info]: <doc:SearchRequest/userInfo>
  /// [google.cloud.retail.v2.UserEventService.CollectUserEvent]: <doc:UserEventServiceClient/collectUserEvent(request:options:)>
  /// [google.cloud.retail.v2.UserInfo.direct_user_request]: <doc:UserInfo/directUserRequest>
  public var ipAddress: Swift.String = Swift.String()

  /// User agent as included in the HTTP header.
  /// The field must be a UTF-8 encoded string with a length limit of 1,000
  /// characters. Otherwise, an INVALID_ARGUMENT error is returned.
  ///
  /// This should not be set when using the client side event reporting with
  /// GTM or JavaScript tag in
  /// [UserEventService.CollectUserEvent][google.cloud.retail.v2.UserEventService.CollectUserEvent]
  /// or if
  /// [direct_user_request][google.cloud.retail.v2.UserInfo.direct_user_request]
  /// is set.
  ///
  /// [google.cloud.retail.v2.UserEventService.CollectUserEvent]: <doc:UserEventServiceClient/collectUserEvent(request:options:)>
  /// [google.cloud.retail.v2.UserInfo.direct_user_request]: <doc:UserInfo/directUserRequest>
  public var userAgent: Swift.String = Swift.String()

  /// True if the request is made directly from the end user, in which case the
  /// [ip_address][google.cloud.retail.v2.UserInfo.ip_address] and
  /// [user_agent][google.cloud.retail.v2.UserInfo.user_agent] can be populated
  /// from the HTTP request. This flag should be set only if the API request is
  /// made directly from the end user such as a mobile app (and not if a gateway
  /// or a server is processing and pushing the user events).
  ///
  /// This should not be set when using the JavaScript tag in
  /// [UserEventService.CollectUserEvent][google.cloud.retail.v2.UserEventService.CollectUserEvent].
  ///
  /// [google.cloud.retail.v2.UserEventService.CollectUserEvent]: <doc:UserEventServiceClient/collectUserEvent(request:options:)>
  /// [google.cloud.retail.v2.UserInfo.ip_address]: <doc:UserInfo/ipAddress>
  /// [google.cloud.retail.v2.UserInfo.user_agent]: <doc:UserInfo/userAgent>
  public var directUserRequest: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `UserInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UserInfo().with { $0.userId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let userId = CodingKeys(stringValue: "userId")
    static let ipAddress = CodingKeys(stringValue: "ipAddress")
    static let userAgent = CodingKeys(stringValue: "userAgent")
    static let directUserRequest = CodingKeys(stringValue: "directUserRequest")

    static let _knownKeys: Set<Swift.String> = [
      "userId",
      "ipAddress",
      "userAgent",
      "directUserRequest",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .userId) {
      self.userId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress) {
      self.ipAddress = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .userAgent) {
      self.userAgent = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .directUserRequest) {
      self.directUserRequest = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.userId, forKey: .userId)
    try container.encode(self.ipAddress, forKey: .ipAddress)
    try container.encode(self.userAgent, forKey: .userAgent)
    try container.encode(self.directUserRequest, forKey: .directUserRequest)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.retail.v2.UserInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
